### ISSUE TITLE
可以把解锁的部分 封装成库传到npm吗

### ISSUE THREAD

**Issue by xiandanin** [ix64/unlock-music#10]

**Comment by ix64** [comment]
懒得弄了，当时写的也是模块化的。解密部分在
- [src/plugins/mflac.js](https://github.com/ix64/unlock-music/blob/master/src/plugins/mflac.js)
- [src/plugins/qmc.js](https://github.com/ix64/unlock-music/blob/master/src/plugins/qmc.js)
- [src/plugins/ncm.js](https://github.com/ix64/unlock-music/blob/master/src/plugins/ncm.js)
