### ISSUE TITLE
ncm 格式音轨号信息可能不被识别

### ISSUE THREAD

**Issue by flosacca** [ix64/unlock-music#100]
所有 ncm 文件解锁后，Mp3tag 和 FB2K 均无法正确识别音轨号，但是在 Windows Explorer 中可以正确显示。

版本：v1.6.4

**Comment by flosacca** [comment]
找到原因了，我下载的 ncm 文件保留有 ID3 信息，添加 ID3 信息会导致原来的信息无法被 Mp3tag 和 FB2K 识别，但仍能被 Windows Explorer 识别。添加的 ID3 信息不包含音轨号，因为网易云的 metadata 并没有包含音轨号。

或许可以检测一下 ID3 信息是否存在，若存在则不再添加。

**Comment by ix64** [comment]
可以简单提供一两个本身含有id3信息的ncm文件以供确认吗

**Comment by flosacca** [comment]
[这个文件](https://we.tl/t-liu31dEsVV)本身包含 ID3 信息，但其中不包含封面图片。

**Comment by flosacca** [comment]
6a2b98798bf09fd48dcb4fdf624e7f0ba49b6677 并没有正确修复，现在基本的信息也会识别错误：
- Mp3Tag 和 FB2K 无法识别封面以外的任何信息；
- Windows Explorer 能正确识别音轨号，但是无法正确显示包含非 ASCII 字符的其他信息。

问题来源于调用的包 [browser-id3-writer](https://github.com/egoroof/browser-id3-writer)，这个包有说明：
> Note: the library removes existing ID3 tag (v2.2, v2.3 and v2.4).

根据结果来看，它破坏了已存在的 ID3 标签，但是没有全部移除，有可能是没有移除 ID3v1 的标签。

**Comment by ix64** [comment]
好的，稍后进行验证
