### ISSUE TITLE
用这个程序解密 ncm 后得到的 mp3 文件，foobar2000 看不到音轨号

### ISSUE THREAD

**Issue by ClarkeCheng** [ix64/unlock-music#103]
- 请按照此模板填写，否则可能立即被关闭
- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）

**Bug描述**

我用这个程序解密后foobar2000里是没有音轨号的
![image](https://user-images.githubusercontent.com/17330505/97102234-d0689e00-16de-11eb-92b6-961b3801163c.png)

我又用 [ncmdump](https://github.com/anonymous5l/ncmdump-gui/releases/tag/lastest) 解密同一个 ncm 文件，结果用它解密的就有音轨号
![image](https://user-images.githubusercontent.com/17330505/97102323-613f7980-16df-11eb-80a2-d4a4b769f7d1.png)

**环境信息:**

 - 操作系统和浏览器：win10，chrome80
 - 程序版本：Build 2020/09/23
 - 获取音乐文件所使用的客户端及其版本信息：网易云Windows版2.7.1

**Comment by ix64** [comment]
你好，感谢你的反馈，此Bug确实存在。
是由于重复添加了id3的歌手、标题信息所致，通过Windows属性应是能够成功读取此信息的。
将抽空修复此问题。
