### ISSUE TITLE
转换QQ音乐的*.[mqms2].qmcflac格式歌曲不完整问题

### ISSUE THREAD

**Issue by hjsprite** [ix64/unlock-music#104]
转换QQ音乐的*.[mqms2].qmcflac歌曲，显示转换成功，但播放到3/4时，歌曲突然结束。部分首歌曲存在此问题，部分歌曲不存在此问题。
举例：QQ音乐中的 五条人 - Last Dance (Live) [mqms2].qmcflac和五条人 - 地球仪 (Live) [mqms2].qmcflac
WIN 10 下Eage Chrome现象相同。

**Comment by ix64** [comment]
请按照Bug报告模板，提供完整的信息

**Comment by hjsprite** [comment]
抱歉，刚才又回溯了一遍，发现时手机OTG BUG导致导出文件时不完整所致。
