### ISSUE TITLE
[建议]已解锁音乐可以zip打包下载

### ISSUE THREAD

**Issue by eatenid** [ix64/unlock-music#105]
- 请按照此模板填写，否则可能立即被关闭

### 背景和说明

> 简要说明产生此想法的背景和此想法的具体内容

我有很多未解密的音乐文件，当我把它们解密后，浏览器下载列表就会被挤爆（“下载全部”和“立即保存”都是如此），想找以前下载的文件要翻好远...(而且太远的下载记录会被清除)  
  
所以我希望能够增加一个"zip打包保存"的功能(姑且先这么叫着吧)

### 实现途径

> - 如果没有设计方案，请简要描述实现思路
> - 如果你没有任何的实现思路，请通过Telegram进行讨论

#### 大致思路：
可以在界面上设个checkbox作为这个功能的开关，开启时点"下载全部"时就以zip文件形式批量打包下载，不开启时就像老样子*~~一个一个地~~*一股脑下载一大堆。  
    
至于内存问题，应该可以在这个模式下，解密完一首后马上添加到zip文件中，原来的数据就丢弃掉，内存使用基本上不会因为zip文件暴增。不过这样子做的话“立即保存”就无法实现了(原来的数据扔了)(都批量下载了也没必要用“立即保存”了吧)  
  
*对js只是懂点皮毛，理解不深，想法也许会有些考虑不到位的地方(´･_･`)，思路可以参考一下*

### 附加信息

> 更多你想要表达的内容

不知道go重写的版本会怎么实现，如果是离线运行不部署到服务器，浏览器做前端go做后端的话，倒是可以让go来直接操作文件系统来保存了，这个需求就没有必要了  
~~在这方面go解决了前端js的不少问题呢😆~~

**Comment by ix64** [comment]
感谢提出建议，将会在下一版本进行实现

**Comment by ix64** [comment]
抱歉哈，此更改设计架构的调整，将计划推迟

**Comment by eatenid** [comment]
没事，问题不大，毕竟不是刚需

**Comment by ix64** [comment]
经过尝试web版本还是不适合大批量转换，保存。
对于大批量转换建议使用CLI版本，目前正在开发中 https://github.com/unlock-music/cli
