### ISSUE TITLE
建议增加批量下载功能

### ISSUE THREAD

**Issue by offline1993** [ix64/unlock-music#107]
- 请按照此模板填写，否则可能立即被关闭

**背景和说明**

在使用过程中发现，如果同时转N个文件，那需要保存N次

比如我解锁100手歌，就需要弹窗100次，点击100次保存

实际上，可以点击一次，将该批文件下载到同一个目录

**Comment by ix64** [comment]
浏览器行为不受程序控制；可以关闭浏览器的下载弹窗，默认保存

**Comment by offline1993** [comment]
好的，感谢
