### ISSUE TITLE
[建议]希望加入酷狗音乐专有歌词格式krc到lrc的转化

### ISSUE THREAD

**Issue by Winson-Huang** [ix64/unlock-music#108]
**背景和说明**

酷狗音乐音频文件已经可以正常转化, 但无法转化转有的歌词文件, 希望加入这个功能, 谢谢!

**实现途径**

- 如果没有设计方案，请简要描述实现思路
- 如果你没有任何的实现思路，请通过Telegram进行讨论

**附加信息**

更多你想要表达的内容

**Comment by ix64** [comment]
本项目暂不考虑添加非音乐文件的转换，可以尝试寻找其他项目
