### ISSUE TITLE
希望增加bkc格式

### ISSUE THREAD

**Issue by fevenor** [ix64/unlock-music#11]
QQ音乐马甲MOO音乐，加密格式为.bkcmp3/.bkcflac，测试重命名为.qmc3/.qmcflac后可解锁。

**Comment by fevenor** [comment]
[已部署测试](https://um.fevenor.com/)，.bkcmp3/.bkcflac解码及在线播放正常，但下载时后缀未修改。
[样本文件](https://c-t.work/s/7614f9565e6d4a)

**Comment by ix64** [comment]
在 https://github.com/ix64/unlock-music/commit/4cd5b45986b5e6f92b0d25e127f01c95db1e5a55 中，已经修复了

**Comment by lizhi520** [comment]
> 
> 
> [已部署测试](https://um.fevenor.com/)，.bkcmp3/.bkcflac解码及在线播放正常，但下载时后缀未修改。
> [样本文件](https://c-t.work/s/7614f9565e6d4a)

样本文件过期了
