### ISSUE TITLE
部分mflac文件解密报错

### ISSUE THREAD

**Issue by gongxw** [ix64/unlock-music#110]
**Bug描述**

部分mflac文件解密报错```TypeError: Cannot read property 'length' of undefined```

**复现方法**

复现文件

[周杰伦 - 青花瓷.zip](https://github.com/ix64/unlock-music/files/5558619/-.zip)

**程序截图或者Console报错信息**

console保存log

[localhost-1605686468371.log](https://github.com/ix64/unlock-music/files/5558603/localhost-1605686468371.log)

[localhost-1605686880166.log](https://github.com/ix64/unlock-music/files/5558647/localhost-1605686880166.log)

**环境信息:**

 - 操作系统和浏览器：Windows10 & Google Chrome 86.0.4240.198  64 位
 - 程序版本：master分支编译版本 nginx1.18.0运行
 - 获取音乐文件所使用的客户端及其版本信息：最新QQ音乐

**Comment by ix64** [comment]
感谢提供信息，将尽快进行测试和修复


--------------原始邮件--------------
发件人："gongxw "<notifications@github.com&gt;;
发送时间：2020年11月18日(星期三) 下午4:11
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ix64/unlock-music] 部分mflac文件解密报错 (#110)
-----------------------------------

 

 
Bug描述
 
部分mflac文件解密报错TypeError: Cannot read property 'length' of undefined
 
复现方法
 
复现文件
 
周杰伦 - 青花瓷.zip
 
程序截图或者Console报错信息
 
console保存log
 
localhost-1605686468371.log
 
localhost-1605686880166.log
 
环境信息:
  
操作系统和浏览器：Windows10 &amp; Google Chrome 86.0.4240.198  64 位
 
程序版本：master分支编译版本 nginx1.18.0运行
 
获取音乐文件所使用的客户端及其版本信息：最新QQ音乐

**Comment by ix64** [comment]
提供的文件署于 #51 所提及的一致，请管着此Issue
