### ISSUE TITLE
meta信息读取错误

### ISSUE THREAD

**Issue by ShawnGaul** [ix64/unlock-music#115]
最近下载了一首延禧攻略OST专辑里面的歌，苏青的相忘，但是读取到的信息是张惠妹的……

**Comment by ix64** [comment]
meta信息是由音频文件提供商填充的，与程序设计勿关

**Comment by ix64** [comment]
另，请按照Template填写Issue

**Comment by ShawnGaul** [comment]
文件在这
链接：https://pan.baidu.com/s/1kNxLkllKXS7poT3_22UdPQ 
提取码：bvke
