### ISSUE TITLE
是否可以实现保留音乐专辑内顺序？

### ISSUE THREAD

**Issue by ShawnYang777** [ix64/unlock-music#118]
您好😁
**背景和说明**

一些音乐专辑中的单曲有特定的顺序，转码后会打乱顺序。

**实现途径**

- 如果没有设计方案，请简要描述实现思路
- 如果你没有任何的实现思路，请通过Telegram进行讨论

**附加信息**

更多你想要表达的内容

**Comment by ix64** [comment]
请说明使用环境，例如解锁什么客户端生成的加密文件；说明顺序信息从何而来；

**Comment by ShawnYang777** [comment]
1、解锁网易云客户端的ncm文件。
2、不清楚ncm文件内部是否有保存顺序信息，但其他从网易云下载的音频通过iTunes读取，可以看到两个信息：音轨和光盘编号。前者就是专辑内的顺序。

**Comment by ix64** [comment]
你好，`.ncm`文件本身不包含光盘编号信息；
但是如果解锁后的原始ID3/FlacMeta之中包含此类信息的话，v1.7.1版本开始是会进行保留的，请尝试更新到此版本
