### ISSUE TITLE
双击执行unlock-kugou-windows-amd64时, 目录下200多首歌, 只执行了67首

### ISSUE THREAD

**Issue by zhaozhongyu** [ix64/unlock-music#119]
- 请按照此模板填写，否则可能立即被关闭
- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）

**Bug描述**

简要地复述你遇到的Bug

**复现方法**

描述复现方法，必要时请提供样本文件

**程序截图或者Console报错信息**

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器：
 - 程序版本：
 - 获取音乐文件所使用的客户端及其版本信息：

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
@zhaozhongyu 请按照模板填写，提供程序运行（或产生结果）的截图；归纳未进行转换的文件的共同特征，等有意义的，对定位问题有帮助的信息

**Comment by ix64** [comment]
请修改后重新open
