### ISSUE TITLE
首先感谢您，下载编译的.exe ，可以解.kgtemp文件，但是我自己根据代码用DELPHI实现不行。

### ISSUE THREAD

**Issue by vasto323** [ix64/unlock-music#123]
感谢您的辛勤劳动。
我下载了Src 来阅读，并改造成 Delphi程序。
 let key1 = new Uint8Array(17)
    key1.set(oriData.slice(0x1c, 0x2c), 0)
    if (MaskV2 == null) {
        if (!await LoadMaskV2()) {
            return {status: false, message: "加载Kgm/Vpr Mask数据失败"}
        }
    }

    for (let i = 0; i < dataLen; i++) {
        let med8 = key1[i % 17] ^ audioData[i]
        med8 ^= (med8 & 0xf) << 4

        let msk8 = GetMask(i)
        msk8 ^= (msk8 & 0xf) << 4
        audioData[i] = med8 ^ msk8
    }

也按照这个流程，跳过1024个字节，逐个hex来 解密，可得出的文件和您编译过的 .exe 解码结果不一样。
不知道哪里出错。
稍后我贴的 kgtemp和解出来的正确、错误的Hex。

**Comment by ix64** [comment]
你好，非此项目的问题，请通过Discussion、邮件、Telegram等其他途径联系。
此Issue将移动至Discussion
