### ISSUE TITLE
modern 1.7.0 解KGV ersion:9106

### ISSUE THREAD

**Issue by vasto323** [ix64/unlock-music#124]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

部署了 modern v1.7.0 ，尝试KG 9106版本的temp文件，导出MP3后不能播放，但是用 unlock-kugou-windows-amd64-beta1.exe 直接解，发现可以播放。

**复现方法**

描述复现方法，必要时请提供样本文件

**程序截图或者Console报错信息**

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器：Win2012，浏览器 IE Edge
 - 程序版本：modern V1.7.0
 - 获取音乐文件所使用的客户端及其版本信息：KG V9106

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
请提供可以复现此问题的样本文件
