### ISSUE TITLE
为什么audio判断长度？

### ISSUE THREAD

**Issue by legiorange** [ix64/unlock-music#125]
当我看到你代码里有
audioData.byteLength > 1 << 26的时候，我解析了一下发现大文件转换也没有任何问题啊。

**Comment by ix64** [comment]
> 当我看到你代码里有
> audioData.byteLength > 1 << 26的时候，我解析了一下发现大文件转换也没有任何问题啊。

此项目中附带的kgm.mask最多只能generate出64MB的Mask数据，超过此长度不能保证正确性

**Comment by ix64** [comment]
https://github.com/ix64/unlock-music/blob/55b2f17ed77803df070eda943f4b6de40dfb9b1e/src/decrypt/kgm.js#L82-L84

https://github.com/ix64/unlock-music/blob/master/public/static/kgm.mask
