### ISSUE TITLE
希望可以直接转换为mp3格式或常见音乐格式

### ISSUE THREAD

**Issue by geekZZJ** [ix64/unlock-music#129]
**背景和说明**

QQ音乐mgg格式转换为mp3格式或者常见音乐格式

**实现途径**
- 目前只能解锁为ogg格式类型
- 希望增加步骤可以转换为mp3或者一步直接转换为mp3格式

**附加信息**

更多你想要表达的内容

**Comment by ix64** [comment]
与 https://github.com/ix64/unlock-music/issues/81 重复
此工具不考虑进行涉及音频重采样的操作，请详细了解解锁和转换格式之间的区别。此类需求请使用专业工具ffmpeg等。
