### ISSUE TITLE
部分QQ音乐下载的 .mflac 格式文件，无法正常解锁

### ISSUE THREAD

**Issue by yaxisvip** [ix64/unlock-music#134]
**Bug描述**

部分QQ音乐下载的 .mflac 格式文件，无法正常解锁

**复现方法**

描述复现方法，必要时请提供样本文件

**程序截图或者Console报错信息**

{status: false, message: "mflac格式仅提供实验性支持", rawExt: "mflac", rawFilename: "张惠妹 _ 张雨生 - 最爱的人伤我最深"}message: "mflac格式仅提供实验性支持"rawExt: "mflac"rawFilename: "张惠妹 _ 张雨生 - 最爱的人伤我最深"status: false__proto__: Object
app.319aaba4.js:1 mflac格式仅提供实验性支持 张惠妹 _ 张雨生 - 最爱的人伤我最深.mflac
showFail @ app.319aaba4.js:1
showSuccess @ app.319aaba4.js:1
re @ chunk-vendors.56f18896.js:27
r @ chunk-vendors.56f18896.js:27
re @ chunk-vendors.56f18896.js:27
Ar.t.$emit @ chunk-vendors.56f18896.js:27
(anonymous) @ app.319aaba4.js:1
Promise.then (async)
handleDoFile @ app.319aaba4.js:1
handleFile @ app.319aaba4.js:1
handleStart @ chunk-vendors.56f18896.js:289
(anonymous) @ chunk-vendors.56f18896.js:289
uploadFiles @ chunk-vendors.56f18896.js:289
re @ chunk-vendors.56f18896.js:27
r @ chunk-vendors.56f18896.js:27
re @ chunk-vendors.56f18896.js:27
Ar.t.$emit @ chunk-vendors.56f18896.js:27
onDrop @ chunk-vendors.56f18896.js:289
drop @ chunk-vendors.56f18896.js:289
re @ chunk-vendors.56f18896.js:27
r @ chunk-vendors.56f18896.js:27
Jn.a._wrapper @ chunk-vendors.56f18896.js:27

**环境信息:**

 - 操作系统和浏览器：Windows 10 20H2 64位 Chrome 87
 - 程序版本：1.7.2
 - 获取音乐文件所使用的客户端及其版本信息：17.73.5336.0629

**附加信息**

这是不能解锁的歌曲列表：

陈奕迅 - 陪你度过漫长岁月-.mflac
大张伟 - 让我坠入爱的漩涡.mflac
福禄寿FloruitShow - 我用什么把你留住 (Live).mflac
金莎 - 星月神话.mflac
鹿晗 - 勋章.mflac
彭佳慧 - 相见恨晚.mflac
张雨生 - 口是心非.mflac
张雨生 _ 张惠妹 - 最爱的人伤我最深.mflac

**Comment by ix64** [comment]
按格式提交Issue；已有相同Issue #51
