### ISSUE TITLE
希望能有chrome浏览器的扩展程序

### ISSUE THREAD

**Issue by SHAORF** [ix64/unlock-music#135]
- 请按照此模板填写，否则可能立即被关闭

**背景和说明**

扩展程序挺好用的，现在从github上下载挺费劲的

**实现途径**

- 如果没有设计方案，请简要描述实现思路
- 如果你没有任何的实现思路，请通过[Discussions](https://github.com/ix64/unlock-music/discussions)或者Telegram进行讨论

**附加信息**

更多你想要表达的内容

**Comment by zwb83925462** [comment]
Chrome扩展格式(crx)可用的的清单文件用于打包crx/nex扩展文件,文件名为manifest.json
清单代码如下:
`{
   "description": "在任何设备上解锁已购的加密音乐！支持QQ音乐与网易云音乐！",
   "icons": {
      "128": "./img/icons/android-chrome-192x192.png"
   },
   "manifest_version": 2,
   "name": "音乐解锁",
   "offline_enabled": true,
   "chrome_url_overrides" : {
     "newtab": "./index.html"
  },
   "permissions": [ "tabs", "bookmarks", "unlimitedStorage", "*://*" ],
   "version": "1.7.2"
}`

**Comment by ix64** [comment]
已经完成相应的适配工作了，正在等待Chrome Web Store审核

**Comment by SHAORF** [comment]
哇!真是太棒了！

**Comment by ix64** [comment]
Microsoft Edge 商店已通过审核 https://microsoftedge.microsoft.com/addons/detail/%E9%9F%B3%E4%B9%90%E8%A7%A3%E9%94%81/ggafoipegcmodfhakdkalpdpcdkiljmd

**Comment by ix64** [comment]
Chrome Web Store 审核通过 https://chrome.google.com/webstore/detail/gldlhhhmienbhlpkfanjpmffdjblmegd

**Comment by ameaninglessname** [comment]
什么？还有这种好事？ 可以给火狐也整一个嘛🥺

**Comment by ix64** [comment]
![image](https://user-images.githubusercontent.com/13902388/108089248-59ec1380-70b4-11eb-8e59-ebfcdefb0bf7.png)
Firefox Addons 正在审核

> 什么？还有这种好事？ 可以给火狐也整一个嘛🥺

**Comment by ix64** [comment]
Firefox Addons 审核通过 https://addons.mozilla.org/zh-CN/firefox/addon/unlock-music/
