### ISSUE TITLE
虾米的一些MP3 无法解锁

### ISSUE THREAD

**Issue by torainyang** [ix64/unlock-music#139]
* 请按照此模板填写，否则可能立即被关闭

- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [x] 我有证据表明这是程序导致的问题（如不确认，可以在[Discussions](https://github.com/ix64/unlock-music/discussions)内提出）

**Bug描述**

简要地复述你遇到的Bug

**复现方法**

描述复现方法，必要时请提供样本文件

**程序截图或者Console报错信息**

如果可以请提供二者之一

**环境信息:**

 - 操作系统和浏览器： win7 / Chrome
[肖邦-夜曲-Op.9-No.1-李云迪.zip](https://github.com/ix64/unlock-music/files/5939805/-.-Op.9-No.1-.zip)
[肖邦-夜曲-Op.9-No.1-李云迪.zip](https://github.com/ix64/unlock-music/files/5939807/-.-Op.9-No.1-.zip)

 - 程序版本：
 - 获取音乐文件所使用的客户端及其版本信息：

**附加信息**

其他能够帮助确认问题的信息

**Comment by ix64** [comment]
你好，感谢提供信息。根据排查，发现引发此问题的是：MusicMetadata依赖返回异常结果导致的。暂时难以解决。
当前，CLI程序能够正常处理此文件，建议使用 https://github.com/unlock-music/cli/releases/tag/v0.0.1

**Comment by ix64** [comment]
[肖邦-夜曲-Op.9-No.1-李云迪.zip](https://github.com/ix64/unlock-music/files/5940036/-.-Op.9-No.1-.zip)

**Comment by torainyang** [comment]
非常感谢这么快速回复。请问CLI程序要运行在64位系统上是吗？
现在用的一个十年前的老爷机在处理文件。
公司电脑禁掉了USB口。。。

**Comment by ix64** [comment]
> 非常感谢这么快速回复。请问CLI程序要运行在64位系统上是吗？
> 现在用的一个十年前的老爷机在处理文件。
> 公司电脑禁掉了USB口。。。

针对Windows构建的是32位版本，但是仅WIndows7及更新版本

**Comment by torainyang** [comment]
电脑是win 7, 不过双击windows-386.exe 运行窗口一闪而过， 是不是操作方法不对？不好意思技术小白

**Comment by ix64** [comment]
> 电脑是win 7, 不过双击windows-386.exe 运行窗口一闪而过， 是不是操作方法不对？不好意思技术小白

这是命令行程序，需要在cmd内使用。

**Comment by torainyang** [comment]
非常感谢 会用了
