### ISSUE TITLE
希望增加VIPER HIFI(.vpr)的解密方法

### ISSUE THREAD

**Issue by Ma-S-H** [ix64/unlock-music#14]
VIPER HIFI 酷狗推出，主打HI-RES和DSD，下载的文件都是vpr格式的，目前网上没有解决方案，希望增加！

**Comment by ix64** [comment]
请提供样本

**Comment by Ma-S-H** [comment]
没钱开OneDrive专业版，这个可能需要搭梯子https://1drv.ms/f/s!AjoG6JAmaYpshSPEYTxO4Z8Fmm4S
国内网盘因为限速没传太大的，微云https://share.weiyun.com/5t6gniy

**Comment by ix64** [comment]
找到一个不太成熟的解决方案，而且不适合整合到项目中，暂时提供一个cli工具。
将kgm/kgma/vpr后缀的文件放置到同一目录之中运行即可。
[Windows版本](https://fs.sz2.ixarea.com/unlock-music/build/temp/kgm-vpr-try.7z?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=D8WNA5ILPNTF3Y2IP5FE%2F20200217%2F%2Fs3%2Faws4_request&X-Amz-Date=20200217T095838Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=b4839578ba052cc212b3f65390b322b1c1785699bb2bcaea70aece7c50ae285c)

**Comment by Ma-S-H** [comment]
先致谢，感谢无私奉献。但仍有小问题：
目前观察到的问题主要是两点：1、大部分vpr转换完成后会提示文件过大，有这样提示的文件大小都是80058KB（81979061字节） 2、有一些转换完成后是MP3格式，但是下载的是FLAC的
还有一个情况忘记说了，在VIPER HIFI上面下载的歌无论是FLAC还是DSD均会被加密成vpr，稍后尽量多上传一些样本，并且注明文件原格式

**Comment by ix64** [comment]
> 目前观察到的问题主要是两点：1、大部分vpr转换完成后会提示文件过大，有这样提示的文件大小都是80058KB（81979061字节）
这个问题稍后会尝试解决，因为还没彻底搞明白其加密原理

**Comment by ix64** [comment]
> 2、有一些转换完成后是MP3格式，但是下载的是FLAC的

这个是我疏忽了，输出为MP3后缀的可能是dff格式的，也就是dsd

**Comment by Ma-S-H** [comment]
这个DSD不一定是什么格式，有可能是dsf，有可能是dff，具体还得看他们给的是什么。
其次上传文件可能需要很长一段时间，一直用的手机流量，这里移动网还有点慢

**Comment by Ma-S-H** [comment]
在电脑上能直接用viper hifi，不需要开通会员，但是电脑版功能很少，在安卓系统上面功能比较多

**Comment by Ma-S-H** [comment]
刚才又确认了一下，确实是DSD编码的都会转成mp3

**Comment by ix64** [comment]
> 刚才又确认了一下，确实是DSD编码的都会转成mp3

嗯 只是命名上的问题，直接修改后缀为dff即可。

**Comment by ix64** [comment]
> 这个DSD不一定是什么格式，有可能是dsf，有可能是dff，具体还得看他们给的是什么。
讲真，我对dsd这方面的几乎没有了解。我稍微查查资料。

**Comment by Ma-S-H** [comment]
希望不要嫌我烦（捂脸）刚才测试了一下，把mp3后缀改成dff或dsf后都无法正常播放，我猜测可能是因为跟文件不全有关，毕竟只是知道DSD大概是什么东西，具体也没什么了解

**Comment by ix64** [comment]
> 其次上传文件可能需要很长一段时间，一直用的手机流量，这里移动网还有点慢

那就不用麻烦了，我这里直接安装viper hifi来下载吧

**Comment by Ma-S-H** [comment]
但是电脑版的VIPER HIFI的电脑版只能下载整个专辑，或者可以下载手机版的，手机上面的现在正在做活动，签到送会员，可以试试手机版下载单曲

**Comment by ix64** [comment]
> 希望不要嫌我烦（捂脸）刚才测试了一下，把mp3后缀改成dff或dsf后都无法正常播放，我猜测可能是因为跟文件不全有关，毕竟只是知道DSD大概是什么东西，具体也没什么了解

因为我这边使用也是修改成dff后，直接使用windows10的酷狗uwp就能够播放了。

**Comment by Ma-S-H** [comment]
没事了（捂脸）是我用的播放器的问题，换了一个播放器就能播放了

**Comment by ix64** [comment]
稍微更新了一下 修复了后缀的问题 [Windows](https://fs.sz2.ixarea.com/unlock-music/build/temp/kgm-vpr-try.7z?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=D8WNA5ILPNTF3Y2IP5FE%2F20200217%2F%2Fs3%2Faws4_request&X-Amz-Date=20200217T123443Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=824e328edfdfc3c9e9a5e1954b0e87ef2c0f3310ba31e4d57ace61968c74d063)

**Comment by l186920** [comment]
首先感谢大佬的工作，我试用了您在楼上发布的vpr解码工具的预览版，它只能解码一部分，一般是在总时长的1/2或2/3处无法播放（可能是文件损坏，不确定）。我提供了一些源文件和解码后的结果，希望可以帮助到您改善此问题。@ix64
https://quqi.com/3623852/476

**Comment by ix64** [comment]
> 首先感谢大佬的工作，我试用了您在楼上发布的vpr解码工具的windows预览版，它只能解码一部分，一般是在总时长的1/2或2/3处无法播放（可能是文件损坏，不确定）。

你发的链接打不开。
不过应该是上文提出的问题，最多解密到80MB左右的问题。
这个和mask文件有关，目前mask文件只有80MB，且尚未找到生成规律，有空我再研究研究。

**Comment by l186920** [comment]
应该是吧，实在抱歉链接打不开。
我这里有一些vpr样本及源文件，都大于80MB。看了看文件大小，vpr文件都比源文件大1024字节，希望能帮助到大佬。样本文件比较大，1.55GB。一共3首flac，3首dff(DSD格式)以及各自对应的vpr文件。@ix64
google云盘：https://drive.google.com/open?id=1pSjhtoSMFtqbl74qG4SMemjL_9ZTH5mU
百度云：https://pan.baidu.com/s/164N2F6rTJ8adNp0YO6Mp8Q 提取码：w018 
腾讯微云：https://share.weiyun.com/5OazJDn

**Comment by l186920** [comment]
> > 首先感谢大佬的工作，我试用了您在楼上发布的vpr解码工具的windows预览版，它只能解码一部分，一般是在总时长的1/2或2/3处无法播放（可能是文件损坏，不确定）。
> 
> 你发的链接打不开。
> 不过应该是上文提出的问题，最多解密到80MB左右的问题。
> 这个和mask文件有关，目前mask文件只有80MB，且尚未找到生成规律，有空我再研究研究。

应该是吧，实在抱歉链接打不开。
我这里有一些vpr样本及源文件，都大于80MB。看了看文件大小，vpr文件都比源文件大1024字节，希望能帮助到大佬。样本文件比较大，1.55GB。一共3首flac，3首dff(DSD格式)以及各自对应的vpr文件。@ix64
google云盘：https://drive.google.com/open?id=1pSjhtoSMFtqbl74qG4SMemjL_9ZTH5mU
百度云：https://pan.baidu.com/s/164N2F6rTJ8adNp0YO6Mp8Q 提取码：w018
腾讯微云：https://share.weiyun.com/5OazJDn

**Comment by 2841889196** [comment]
> > 目前观察到的问题主要是两点：1、大部分vpr转换完成后会提示文件过大，有这样提示的文件大小都是80058KB（81979061字节）
> 
> 这个问题稍后会尝试解决，因为还没彻底搞明白其加密原理



> 请提供样本
首先，谢谢大佬的创作。我在使用您的成果过程中，发现只能解密80m的歌曲，浏览上述记录后才知道可能是大佬的样本不够。因此，我想提供几十g的vpr样本，其中绝大多数是100m以上的，望大佬早日做出较完美的产品。谢谢。
链接：https://pan.baidu.com/s/1VjSiZA5qY03XuJcwJTfiMA
提取码：1k4g
另外，虽然像你这样的大佬都不缺钱，但我仍想打赏100元，表达心意，这是我的微信号17718131068，如果做出来了，请加我微信，我发个红包，虽然大佬都不缺钱，但这是心意。

**Comment by 2841889196** [comment]
希望大佬早日成功，真的很需要，谢谢。

**Comment by ix64** [comment]
感谢关注，我将尽快继续相关研究

**Comment by ix64** [comment]
Alpha-3 Build 2020/05/03 版本已更新，支持220MB以下文件解锁。
[https://github.com/ix64/unlock-music/wiki/其他音乐格式工具#酷狗音乐-kgmvpr解锁工具](https://github.com/ix64/unlock-music/wiki/%E5%85%B6%E4%BB%96%E9%9F%B3%E4%B9%90%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%85%B7#%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90-kgmvpr%E8%A7%A3%E9%94%81%E5%B7%A5%E5%85%B7)

**Comment by ix64** [comment]
如果有比220MB更大的文件，欢迎提供相应的歌曲、歌手信息。

**Comment by l186920** [comment]
我这里有一些vpr样本及源文件，都大于220MB。样本文件比较大，6.04GB。一共3首flac，3首dff(DSD格式)以及各自对应的vpr文件。其中有flac达到了1gb左右，dsd普遍500mb左右。考虑到文件较大，每个文件在压缩前做了文件校验，写了文件的校验值放在压缩包里。
请下载时用一下梯子吧，我把文件放在我个人基于onedrive的云盘里https://yun.kms233.com/vpr%E6%A0%B7%E6%9C%AC/
@ix64大佬近期辛苦了，放弃假日开发，无以为报，就祝您身体安康，学业有成，事业成功。

**Comment by ix64** [comment]
@l186920 好的 感谢提供

**Comment by ix64** [comment]
[Beta-1 Build 2020/05/06](https://tool.ixarea.com/music/download/kugou/) 已更新
- 升级算法。现在通过92KB的数据来生成1.08GB的Mask，并优化了内存占用
- 内嵌数据。现在无需另外下载Mask文件

**Comment by ix64** [comment]
预计近期将会合并到主项目中

**Comment by l186920** [comment]
大佬辛苦了！

**Comment by David-H-1** [comment]
感谢大佬！

**Comment by zhuliangyi** [comment]
> Alpha-3 Build 2020/05/03 版本已更新，支持220MB以下文件解锁。
> [https://github.com/ix64/unlock-music/wiki/其他音乐格式工具#酷狗音乐-kgmvpr解锁工具](https://github.com/ix64/unlock-music/wiki/%E5%85%B6%E4%BB%96%E9%9F%B3%E4%B9%90%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%85%B7#%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90-kgmvpr%E8%A7%A3%E9%94%81%E5%B7%A5%E5%85%B7)

大佬你好，这个下载完之后没有执行文件啊~

**Comment by zhuliangyi** [comment]
> Alpha-3 Build 2020/05/03 版本已更新，支持220MB以下文件解锁。
> [https://github.com/ix64/unlock-music/wiki/其他音乐格式工具#酷狗音乐-kgmvpr解锁工具](https://github.com/ix64/unlock-music/wiki/%E5%85%B6%E4%BB%96%E9%9F%B3%E4%B9%90%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%85%B7#%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90-kgmvpr%E8%A7%A3%E9%94%81%E5%B7%A5%E5%85%B7)

大佬你好，这个下载完之后没有执行文件啊~

**Comment by zhuliangyi** [comment]
大佬现在我能用的就还是只有78M以下的 解锁。78以上的DSD文件的那个CLI版，不知道怎么操作啊~下载后没有能够执行的文件

**Comment by zhuliangyi** [comment]
> [Beta-1 Build 2020/05/06](https://tool.ixarea.com/music/download/kugou/) 已更新
> 
> * 升级算法。现在通过92KB的数据来生成1.08GB的Mask，并优化了内存占用
> * 内嵌数据。现在无需另外下载Mask文件

这个链接打不开了。

**Comment by ix64** [comment]
你好，kgm/vpr工具已并入cli。kgm/vpr工具原本的下载连接，由于服务器迁移，暂时导致不可用

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："zhuliangyi ***@***.***&gt;;
发送时间：2021年3月13日(星期六) 上午10:33
收件人："ix64/unlock-music" ***@***.***&gt;;
抄送："MengYX ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [ix64/unlock-music] 希望增加VIPER HIFI(.vpr)的解密方法 (#14)
-----------------------------------

 

  
Beta-1 Build 2020/05/06 已更新
  
升级算法。现在通过92KB的数据来生成1.08GB的Mask，并优化了内存占用
 
内嵌数据。现在无需另外下载Mask文件
   
这个链接打不开了。

**Comment by ix64** [comment]
cli程序，请使用cmd，poweshell等终端运行

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："zhuliangyi ***@***.***&gt;;
发送时间：2021年3月13日(星期六) 上午10:19
收件人："ix64/unlock-music" ***@***.***&gt;;
抄送："MengYX ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [ix64/unlock-music] 希望增加VIPER HIFI(.vpr)的解密方法 (#14)
-----------------------------------

 

 
大佬现在我能用的就还是只有78M以下的 解锁。78以上的DSD文件的那个CLI版，不知道怎么操作啊~下载后没有能够执行的文件

**Comment by zhuliangyi** [comment]
> cli程序，请使用cmd，poweshell等终端运行

**Comment by zhuliangyi** [comment]
> cli程序，请使用cmd，poweshell等终端运行
> […](#)
> ---------- 该邮件从移动设备发送
> --------------原始邮件-------------- 发件人："zhuliangyi ***@***.***&gt;; 发送时间：2021年3月13日(星期六) 上午10:19 收件人："ix64/unlock-music" ***@***.***&gt;; 抄送："MengYX ***@***.***&gt;;"State change ***@***.***&gt;; 主题：Re: [ix64/unlock-music] 希望增加VIPER HIFI(.vpr)的解密方法 (#14) ----------------------------------- 大佬现在我能用的就还是只有78M以下的 解锁。78以上的DSD文件的那个CLI版，不知道怎么操作啊~下载后没有能够执行的文件 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

您好 我下载完了是一个cli-master的文件夹。。。然后怎么操作啊~~希望不会觉得我太烦，确实不太懂 谢谢

**Comment by ix64** [comment]
请查看该项目readme，从release下载预编译版本

----------

该邮件从移动设备发送




--------------原始邮件--------------
发件人："zhuliangyi ***@***.***&gt;;
发送时间：2021年3月14日(星期天) 晚上6:16
收件人："ix64/unlock-music" ***@***.***&gt;;
抄送："MengYX ***@***.***&gt;;"State change ***@***.***&gt;;
主题：Re: [ix64/unlock-music] 希望增加VIPER HIFI(.vpr)的解密方法 (#14)
-----------------------------------

 

  
cli程序，请使用cmd，poweshell等终端运行
 …
 ---------- 该邮件从移动设备发送
 --------------原始邮件-------------- 发件人："zhuliangyi @.&gt;; 发送时间：2021年3月13日(星期六) 上午10:19 收件人："ix64/unlock-music" @.&gt;; 抄送："MengYX @.&gt;;"State change @.&gt;; 主题：Re: [ix64/unlock-music] 希望增加VIPER HIFI(.vpr)的解密方法 (#14) ----------------------------------- 大佬现在我能用的就还是只有78M以下的 解锁。78以上的DSD文件的那个CLI版，不知道怎么操作啊~下载后没有能够执行的文件 — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好 我下载完了是一个cli-master的文件夹。。。然后怎么操作啊~~希望不会觉得我太烦，确实不太懂 谢谢

**Comment by zhuliangyi** [comment]
> 请查看该项目readme，从release下载预编译版本
> […](#)
release里面下的文件夹是cli-0.02   然后我把Windows 386  还有AMD64放在这个文件里执行 。结果闪退。应该怎么操作~

**Comment by zhuliangyi** [comment]
说明里说的那个~ how to build  我也没太懂
# Unlock Music Project - CLI Edition
Original: Web Edition https://github.com/ix64/unlock-music
- [Release Download](https://github.com/unlock-music/cli/releases/latest)

## Features
- [x] All Algorithm Supported By `ix64/unlock-music`
- [ ] Complete Cover Image
- [ ] Parse Meta Data
- [ ] Complete Meta Data

## Hou to Build
- Requirements: **Golang 1.16**

1. Clone this repo `git clone https://github.com/unlock-music/cli && cd cli`
2. Build the executable `go build ./cmd/um` 

## How to use
- Use `./um -h` to show help menu

**Comment by zhuliangyi** [comment]
大佬~~帮帮忙呀~~~~

**Comment by ix64** [comment]
> 大佬~~帮帮忙呀~~~~

请不要在已关闭的Issue中，发表主题无关消息。你要知道，在此处你每发一条消息都会有不少人收到邮件通知。
有使用方面的帮助请求，请通过 https://github.com/ix64/unlock-music/discussions 或者直接Email联系

**Comment by ix64** [comment]
> 说明里说的那个~ how to build 我也没太懂

**cli程序，请使用cmd，poweshell等终端运行**

> ## How to use
> * Use `./um -h` to show help menu
