### ISSUE TITLE
希望增加酷狗音乐(.kgm/.kgma)的解密方案

### ISSUE THREAD

**Issue by wuhang2003** [ix64/unlock-music#15]
经下载发现酷狗音乐的私有格式主要是kgm（标准/高品质mp3）和kgma（无损音质flac），目前网上没有相对完整的解密方案
测试音频链接：https://c-t.work/s/2fd6d7c3a9334c

**Comment by wuhang2003** [comment]
在网上看到一个[闭源软件](https://mortalworld.net/kgm-download.html)，经测试能转，但是需要付钱
当然Github上也有[破解的办法](https://github.com/OhYee/kgm_cracker)
（不知道能不能提供点帮助

**Comment by ix64** [comment]
好的 感谢提供信息
过几天吧 现在比较懒 :smile:

**Comment by ix64** [comment]
找到一个不太成熟的解决方案，而且不适合整合到项目中，暂时提供一个cli工具。
将kgm/kgma/vpr后缀的文件放置到同一目录之中运行即可。
[Windows版本](https://fs.sz2.ixarea.com/unlock-music/build/temp/kgm-vpr-try.7z?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=D8WNA5ILPNTF3Y2IP5FE%2F20200217%2F%2Fs3%2Faws4_request&X-Amz-Date=20200217T095838Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=b4839578ba052cc212b3f65390b322b1c1785699bb2bcaea70aece7c50ae285c)

**Comment by greatbody** [comment]
实测这个不起作用。

**Comment by ix64** [comment]
请提供样本以或任何有参考意义的信息


--------------原始邮件--------------
发件人："Rui Sun "<notifications@github.com&gt;;
发送时间：2020年4月20日(星期一) 晚上10:18
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："MengYX "<admin@mengyx.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [ix64/unlock-music] 希望增加酷狗音乐(.kgm/.kgma)的解密方案 (#15)
-----------------------------------

 

 
实测这个不起作用。

**Comment by greatbody** [comment]
稍等，晚些时候上传。
