### ISSUE TITLE
关于QQ音乐新的加密音乐格式

### ISSUE THREAD

**Issue by wqh227** [ix64/unlock-music#18]
其实在post获取文件地址的时候可以发现，同时返回的时候也附带的了一串base64加密的字符（但是无法解密，我猜是一个突破口），不知道对于你破解有没有用。

**Comment by wqh227** [comment]
{"code":0,"ts":1581151629098,"queryvkey":{"code":0,"data":{ "expiration": 80400, "login_key": "", "midurlinfo": [ { "common_downfromtag": 139, **_### "ekey": "OHI2MDFCdnUogdwI2vrP0kdnVphz3V+yOUHQ6xfJXoMqCggLxPGwWW9HQ5xWbwIjhy+ykaWgaXIQjIHb7PGBqmnuSZMGPXJjtarbaDN\/do1jVSQRN\/JPlHVaquQqtbUUGGtFJn5XbBqzSb\/O8i6GSBh4cFdeCkk+ApqgD4ruZIlWh7VCPRCrcPVNoP+hO4r7cRyLh3\/3Yt7oUnwxdlDVcZt1QIGDPzcE0lDyemm5BGjIlYraiWZ1QHBPD9Id\/Tq022OL4iCYAdibnzultCoccXYa1dFJW+6exPTZqRLLJkgyUQe6PrGERLAEusn02EOCG2G5CPnbT8QlSzsYuoE2GoBqOJcNVy0uVNPhbQVwPEg="_**, "errtype": "", "filename": "O6M00000HxwU1V81tL.mgg", "flowfromtag": "", "flowurl": "", "hisbuy": 0, "hisdown": 0, "isbuy": 0, "isonly": 0, "onecan": 1, "opi128kurl": "", "opi192koggurl": "", "opi192kurl": "", "opi30surl": "", "opi48kurl": "", "opi96kurl": "", "opiflackurl": "", "p2pfromtag": 83, "pdl": 0, "pneed": 0, "pneedbuy": 1, "premain": 0, "purl": "O6M00000HxwU1V81tL.mgg?guid=DF4D2BA86EFE0FE2126D6E28EC63327D&vkey=69F005062675F0E5AF43FADFA17B399677F73A5A3FEE16542D701519489E1075982EF572F7F01D758A9F5F1D8FE38C2236AC4C217B7AE489&uin=0", "qmdlfromtag": 75, "result": 0, "songmid": "0000HxwU1V81tL", "tips": "", "uiAlert": 0, "vip_downfromtag": 140, "vkey": "69F005062675F0E5AF43FADFA17B399677F73A5A3FEE16542D701519489E1075982EF572F7F01D758A9F5F1D8FE38C2236AC4C217B7AE489", "wififromtag": "", "wifiurl": "" } ], "msg": "114.92.11.226", "retcode": 0, "servercheck": "bce72a40592cd54f797e25f7b836727a", "sip": [  ], "testfile2g": "", "testfilewifi": "", "thirdip": [ "", "" ], "uin": "", "verify_type": 0 }}}

**Comment by wqh227** [comment]
一个文件不同的账号访问ekey也是一样的，不同文件ekey不同
这是post地址
hxxps://u.y.qq.com/cgi-bin/musicu.fcg
{
    "comm": {
        "ct": "19",
        "cv": "1724",
        "patch": "118",
        "uin": "0",
        "wid": "0"
    },
    "queryvkey": {
        "method": "CgiGetEVkey",
        "module": "vkey.GetEVkeyServer",
        "param": {
            "checklimit": 0,
            "ctx": 1,
            "downloadfrom": 0,
            "filename": ["O6M00000HxwU1V81tL.mgg"],
            "guid": "DF4D2BA86EFE0FE2126D6E28EC63327D",
            "musicfile": ["O6M00000HxwU1V81tL.mgg"],
            "nettype": "",
            "referer": "y.qq.com",
            "scene": 0,
            "songmid": ["0000HxwU1V81tL"],
            "songtype": [1],
            "uin": ""
        }
    }
}

**Comment by ix64** [comment]
嗯，发现了，这一段base64和嵌在mflac/mgg文件末端的base64是一致的，应该就是密匙信息。但目前还没找到解读的方法。

**Comment by ix64** [comment]
mgg格式已支持。
