### ISSUE TITLE
歌曲命名格式

### ISSUE THREAD

**Issue by w316525096** [ix64/unlock-music#19]
希望在网页里的"歌曲命名格式"加一项命名方式:按原始文件命名(不改变文件名称).

  比如这专辑unlock后，有重名。
Johann Sebastian Bach - Bach： Cello Suites
https://c.y.qq.com/base/fcgi-bin/u?__=i1JyH4I

**Comment by ix64** [comment]
嗯，有道理。下一次更新的时候，一起加上吧。
