### ISSUE TITLE
在线部署失败

### ISSUE THREAD

**Issue by dukecd33369** [ix64/unlock-music#24]
npm install 就报错了 用到了fsevents 这个在ubuntu的机器上装不上诶

**Comment by ix64** [comment]
应该不是项目的问题。
我本人使用Ubuntu18.04。[CI服务器](https://ci.ixarea.com/ix64/unlock-music/74/1/2)使用的 Node Docker(Debain9)。
目前都是没有问题的。

建议检查一下npm缓存和设置。

**Comment by dukecd33369** [comment]
我也是18.04
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
报了这个

**Comment by ix64** [comment]
> npm **WARN optional SKIPPING OPTIONAL DEPENDENCY**: fsevents@1.2.11 (node_modules/fsevents):

看清楚 这只是自动跳过不符合要求的**可选依赖**，不会造成部署失败

**Comment by dukecd33369** [comment]
npm ERR! code ELIFECYCLE
npm ERR! errno 137
npm ERR! unlock-music@1.3.2 build: `vue-cli-service build`
npm ERR! Exit status 137
npm ERR!
npm ERR! Failed at the unlock-music@1.3.2 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

我这是不是内存不足了？

**Comment by ix64** [comment]
应该是，可以尝试使用 `npm ci` 来安装

**Comment by dukecd33369** [comment]
> 
> 
> 应该是，可以尝试使用 `npm ci` 来安装

可以诶  查了下ci是npm 6的安装方式？这就可以了

**Comment by dukecd33369** [comment]
哦 不对 5.7.0开始的

**Comment by ix64** [comment]
也可能是你npm install过程中网络出错，导致安装不完整。这时应该用 npm clean-install

**Comment by ttimasdf** [comment]
部署并不需要自己build呀，，这是个静态的web应用，用release里的压缩包，放Github Pages上面都能跑起来，
