### ISSUE TITLE
本应用未经同意泄露用户隐私信息，请提供关闭选项

### ISSUE THREAD

**Issue by ttimasdf** [ix64/unlock-music#28]
当前本应用收集了很多本不该收集的关键用户隐私信息，虽然作为非营利项目，对这类行为表示理解，但希望能够提供一个开关能够关闭这些信息的收集，至少不要收集这么多是吧。

当前（以版本 [v1.3.3](https://github.com/ix64/unlock-music/releases/tag/1.3.3) 为例），本应用会向 `stats.ixarea.com` 泄露以下信息。

- 使用者**公网IP**。
- User-Agent：包括**浏览器、操作系统版本**。如果是手机，还会包括**设备型号**或**微信版本**。
- Referer：用户自行搭建应用时使用的**内网IP、域名或VPS地址**。
- 用户上传转码的**每首歌曲**的**所有信息**。
  - 歌手
  - 专辑名称
  - 歌名
  - 原始文件名
  - 文件格式
  - 有一个字段没细看，会不会是用户的解密密钥？
  - [也许还有更多，直接在项目里搜索stats.ixarea.com即可，毕竟是开源的](https://github.com/ix64/unlock-music/search?q=stats.ixarea.com&unscoped_q=stats.ixarea.com)。

`stats.ixarea.com` 指向IP `39.108.164.4` ，ICP备案号 `粤ICP备15016438号-3`。杭州阿里云。这都是公开信息。你至少套个高防，这样黑产也没那么容易找到你呀。

随便贴一点东西，当然并没有法律效力，[国家互联网信息办公室 数据安全管理办法（征求意见稿）](http://www.moj.gov.cn/news/content/2019-05/28/zlk_235861.html)

```
第二条 在中华人民共和国境内利用网络开展数据收集、存储、传输、处理、使用等活动（以下简称数据活动），以及数据安全的保护和监督管理，适用本办法。纯粹家庭和个人事务除外。
```

```
第八条 收集使用规则应当明确具体、简单通俗、易于访问，突出以下内容：

（一）网络运营者基本信息；
（二）网络运营者主要负责人、数据安全责任人的姓名及联系方式；
（三）收集使用个人信息的目的、种类、数量、频度、方式、范围等；
（四）个人信息保存地点、期限及到期后的处理方式；
（五）向他人提供个人信息的规则，如果向他人提供的；
（六）个人信息安全保护策略等相关信息；
（七）个人信息主体撤销同意，以及查询、更正、删除个人信息的途径和方法；
（八）投诉、举报渠道和方法等；
（九）法律、行政法规规定的其他内容。
```

因此收集信息的目的我们不讨论也罢，至少，希望有一个关闭的选项。

**Comment by ix64** [comment]
在打包前，删除此行
https://github.com/ix64/unlock-music/blob/97ca09dbaef3b322bd86f068d8be72e67f49cf8b/public/index.html#L9
即可关闭向 stats.ixarea.com 报告浏览器相关信息、解锁的信息、程序运行错误信息。
这部分信息通过开源软件Matomo搜集，主要用于程序开发过程中：确定浏览器兼容性、界面适配，发现程序错误和改进程序错误。

另解锁mgg/mflac时，若本地程序无法根据算法探测出Mask信息，将会向 https://stats.ixarea.com/collect/qmcmask 发送查询请求，并在成功解锁后反馈。
这部分请求主要用于帮助用户解锁此类型文件。如需关闭此功能，在打包前，删除以下几行即可。
https://github.com/ix64/unlock-music/blob/4ca45e1233f3b84e1fd536745155229af0b810c9/src/decrypt/qmc.js#L28
https://github.com/ix64/unlock-music/blob/4ca45e1233f3b84e1fd536745155229af0b810c9/src/decrypt/qmc.js#L43-L44
