### ISSUE TITLE
#希望增加批量拖入浏览器解密或者多选解密的功能

### ISSUE THREAD

**Issue by TaoChingChung** [ix64/unlock-music#29]
我开了会员 下了很多的音乐都是qmflac的格式，想全部转换为flac

![image](https://user-images.githubusercontent.com/2031794/76605429-66362b00-654b-11ea-979e-a4706db957bc.png)

  = = 不知道是否可行？

**Comment by TaoChingChung** [comment]
> 多选/批量拖拽，这个功能是在初始版本中就已实现的

咦，我从播放设备拖入Chrome和Firefox都不行 = =

**Comment by ix64** [comment]
你使用的程序版本，操作系统和浏览器版本是什么？
我刚才简单测试了一下 Windows 和 Linux下的 Firefox, Chrome都是可以的，手边没有MacOS，没测试。

**Comment by TaoChingChung** [comment]
> 你使用的程序版本，操作系统和浏览器版本是什么？
> 我刚才简单测试了一下 Windows 和 Linux下的 Firefox, Chrome都是可以的，手边没有MacOS，没测试。

嗯嗯，谢谢。我使用的是昨天刚更新的版本。我刚才又再试了一下，我从电脑上拖进本地的Unlock Music是可以的，但是我从我的MP4上面直接拖进去是不行的 = =
