### ISSUE TITLE
有个新的加密格式mgg，啥时候能支持？

### ISSUE THREAD

**Issue by luzihao1234** [ix64/unlock-music#3]

**Comment by ix64** [comment]
可以提供此格式的文件吗，我没下载到过这个格式的。

**Comment by luzihao1234** [comment]
> 可以提供此格式的文件吗，我没下载到过这个格式的。



> 可以提供此格式的文件吗，我没下载到过这个格式的。

**Comment by xmoer** [comment]
> 可以提供此格式的文件吗，我没下载到过这个格式的。

此格式的确很少见，比如这个：https://y.qq.com/n/yqq/song/000ddRjj0njTSe.html

**Comment by ix64** [comment]
谢谢你，现已找到mgg格式样本，但使用于mflac的解密方法并不适用于mgg，因此短时间内可能不会支持。

**Comment by ix64** [comment]
mgg格式已支持。

**Comment by suheti** [comment]
感谢作者 太牛逼了 搜了一圈搜到你这儿才找到mgg格式的支持

**Comment by huanghe112101** [comment]
转出来以后是OGG格式，好像没有封面，是我自己的原因嘛

**Comment by GoblinXL** [comment]
好像还是不行

**Comment by ix64** [comment]
暂时只有flac和mp3的meta覆盖功能





--------------原始邮件--------------
发件人："huanghe112101 "<notifications@github.com&gt;;
发送时间：2021年2月18日(星期四) 下午3:59
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："MengYX "<admin@mengyx.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [ix64/unlock-music] 有个新的加密格式mgg，啥时候能支持？ (#3)
-----------------------------------

 

 
转出来以后是OGG格式，好像没有封面，是我自己的原因嘛

**Comment by GoblinXL** [comment]
大佬，mgg格式的好像不是每一首都可以解密

**Comment by ix64** [comment]
详见 #51


--------------原始邮件--------------
发件人："GoblinXL "<notifications@github.com&gt;;
发送时间：2021年2月18日(星期四) 下午4:18
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："MengYX "<admin@mengyx.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [ix64/unlock-music] 有个新的加密格式mgg，啥时候能支持？ (#3)
-----------------------------------

 

 
大佬，mgg格式的好像不是每一首都可以解密

**Comment by huanghe112101** [comment]
> 暂时只有flac和mp3的meta覆盖功能
> […](#)
> --------------原始邮件-------------- 发件人："huanghe112101 "<notifications@github.com&gt;; 发送时间：2021年2月18日(星期四) 下午3:59 收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;; 抄送："MengYX "<admin@mengyx.cn&gt;;"Comment "<comment@noreply.github.com&gt;; 主题：Re: [ix64/unlock-music] 有个新的加密格式mgg，啥时候能支持？ (#3) ----------------------------------- 转出来以后是OGG格式，好像没有封面，是我自己的原因嘛 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢大佬回复

**Comment by zanzhao-ai** [comment]
大佬mgg格式不稳定，部分不能解压
