### ISSUE TITLE
部分文件解锁后文件名为乱码

### ISSUE THREAD

**Issue by yourmother233** [ix64/unlock-music#30]
音乐在解锁完成后个别文件会出现乱码

**Comment by ix64** [comment]
请提供样本文件，或者有价值的信息。

**Comment by yourmother233** [comment]
在线上(非本地网页)解锁网易云音乐文件时，会有个别文件出现随机乱码，乱码由四个大写英文字母组成，由于我已经将乱码文件手动改名，所以很抱歉无法提供样本

发送自 Windows 10 版邮件应用

发件人: MengYX
发送时间: 2020年3月15日 19:53
收件人: ix64/unlock-music
抄送: yourmother233; Author
主题: Re: [ix64/unlock-music] 乱码 (#30)

请提供样本文件，或者有价值的信息。
