### ISSUE TITLE
本地部署一直转圈

### ISSUE THREAD

**Issue by Trueham** [ix64/unlock-music#32]
![image](https://user-images.githubusercontent.com/62303914/76886087-34aac000-68bb-11ea-9497-4a94430963c5.png)

**Comment by ix64** [comment]
1. 确认是否使用了`modern`版本，Release Note已明确，本地部署仅能使用`legacy`版本
2. 确认是否使用过旧的浏览器
3. 如已确认以上无问题，请提供操作系统、浏览器版本信息以及Console中的错误信息。

**Comment by Trueham** [comment]
> 1. 确认是否使用了`modern`版本，Release Note已明确，本地部署仅能使用`legacy`版本
> 2. 确认是否使用过旧的浏览器
> 3. 如已确认以上无问题，请提供操作系统、浏览器版本信息以及Console中的错误信息。

感谢,下载legacy已经本地打开.今天凌晨legacy一直下载不动,于是下载的是那两个source code.问题已解决感谢.继续支持你!
