### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by D-Jy-lab** [ix64/unlock-music#33]
安装依赖时
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by ix64** [comment]
https://github.com/ix64/unlock-music/issues/24

**Comment by D-Jy-lab** [comment]
哦哦，打扰您了
