### ISSUE TITLE
建议源码里包含已构建版本，而不是只能在release里下载

### ISSUE THREAD

**Issue by latel** [ix64/unlock-music#35]
这样的话，我就可以部署在nas上，一个git pull就能更新到最新版本了。
不然的话只能手动下载更新或者自己写脚本来弄咯

**Comment by ix64** [comment]
将构建的代码包含在源码中，是不规范的性行为 。这将使得代码仓库剧烈膨胀等不良后果。
故，不考虑接受此建议。但未来将考虑新建独立仓库储存release。
另：现建议通过定时检查 https://api.github.com/repos/ix64/unlock-music/releases/latest 来进行自动更新

**Comment by ix64** [comment]
现已添加`gh-pages`分支, https://github.com/ix64/unlock-music/tree/gh-pages
通过GitHub Action 随Release一同更新
