### ISSUE TITLE
本地部署页面加载不成功

### ISSUE THREAD

**Issue by SArcobalen** [ix64/unlock-music#36]
换了几个浏览器都一样，不知道是不是要加载很久很久的问题。。？

**Comment by ix64** [comment]
1. 确认是否使用了modern版本，Release Note已明确，本地部署仅能使用legacy版本
2. 确认是否使用过旧的浏览器
3. 如已确认以上无问题，请提供操作系统、浏览器版本信息以及Console中的错误信息。

**Comment by ix64** [comment]
Duplicated with #32
