### ISSUE TITLE
添加解锁进度条

### ISSUE THREAD

**Issue by hmsjy2017** [ix64/unlock-music#37]
1.可以用Electron做成全平台软件，这样就能不用打开浏览器了
2.解锁完的音乐🎵前面添加序号，更清楚明了
以上仅个人观点

**Comment by ix64** [comment]
> 1.可以用Electron做成全平台软件，这样就能不用打开浏览器了

关于这个，不考虑使用Electron，过于庞大。正在考虑等有空了使用Golang重写。

**Comment by ix64** [comment]
> 2.解锁完的音乐🎵前面添加序号，更清楚明了

这个可以具体说说那些场景需要依靠序号区分文件吗？

**Comment by hmsjy2017** [comment]
为了知道已解锁文件的数量

**Comment by ix64** [comment]
> 为了知道已解锁文件的数量

我让然不太理解这个功能的价值所在。
你是希望
- 创建一个持久化的变量用于储存这个序号？
- 每次解锁每次访问期间，分配唯一的序号？
- 始终保持序号连续，用户删除解锁记录后序号自动补上？

用户下载的文件时候需要包含序号？

这样的需求，和 **保存文件后，利用文件管理器的统计** 有何区别？

**Comment by hmsjy2017** [comment]
emmm..如果你觉得不好的话，可以不采纳

**Comment by hmsjy2017** [comment]
其实归根结底我是想知道还有多久还有多久能解锁完这么多文件，或许可以显示剩余时间？

**Comment by ix64** [comment]
> emmm..如果你觉得不好的话，可以不采纳

只是在设计功能之前，必须了解这个功能的必要性，使用场景等问题。
例如关于我提出的三种实现可能，你在之前的提议中并无提起，因此无法获知你的真实需求。

**Comment by ix64** [comment]
> 其实归根结底我是想知道还有多久还有多久能解锁完这么多文件，或许可以显示剩余时间？

如果仅是此需求，我认为或者以进度条的形式呈现会更好。

**Comment by hmsjy2017** [comment]
嗯 这样也不错
