### ISSUE TITLE
举报某站未使用开源声明

### ISSUE THREAD

**Issue by LazzyFatty** [ix64/unlock-music#38]
http://www.atoolbox.net/Tool.php?Id=860

**Comment by ix64** [comment]
> http://www.atoolbox.net/Tool.php?Id=860

感谢告知，我将尝试与对方联系。
选择开源的时候，便猜到了会出现这种情况，毕竟协议只是君子协定……

**Comment by EmmmMonster** [comment]
其实还有更过分的 …… 把LICENSE和作者信息去掉，改成自己的名字，就成为他们官方的了……
https://www.btsafety.cn/music/
![微信图片_20200322212900](https://user-images.githubusercontent.com/58943012/77250655-5e5c4200-6c41-11ea-8a15-dc8229f6b2b1.png)

**Comment by ix64** [comment]
@EmmmMonster 好的 谢谢 我尝试联系一下

**Comment by Avrinbai** [comment]
> 其实还有更过分的的……把许可证和作者信息去掉，改成自己的名字，就成为他们官方的了…… [https:](https://www.btsafety.cn/music/) //www.btsafety.cn/music/
> [](https://www.btsafety.cn/music/)
> ![微信图片_20200322212900](https://user-images.githubusercontent.com/58943012/77250655-5e5c4200-6c41-11ea-8a15-dc8229f6b2b1.png)
实在是对不起，我为我的所作所为感到非常抱歉，之前是因为手机端不美观才改成这样的，之后一直在想改回来，因为改版站点就一拖再拖，不过我在我每发站点的平台都有留下开源信息，真的非常抱歉！

**Comment by ix64** [comment]
@EmmmMonster @LazzyFatty 抱歉，近段时间比较忙，直到昨天才向他们发送函告。

**Comment by ix64** [comment]
@Avrinbai 已收到并确认 https://www.btsafety.cn/music/ 中添加了版权和LICENSE信息。感谢您对开源软件的支持。

**Comment by ix64** [comment]
已收到并确认 https://www.btsafety.cn/music/ 中添加了版权和LICENSE信息。
