### ISSUE TITLE
我部署了前端（网页），一直转圈圈

### ISSUE THREAD

**Issue by splendidwrx** [ix64/unlock-music#4]
是不是还需要做些什么后端的部署

**Comment by ix64** [comment]
执行 `npm run build` 后将 dist 目录内容部署即可

**Comment by splendidwrx** [comment]
好的，我尝试一下

**Comment by ix64** [comment]
[Release](https://github.com/ix64/unlock-music/releases/latest)中已经上传构建好的版本，可以直接用于部署或者本地运行。

**Comment by dabo-t** [comment]
下载了Release中已经上传构建好的版本，在本地直接打开index.html。页面显示转圈圈
![image](https://user-images.githubusercontent.com/9606042/70388233-ee0b1700-19e9-11ea-9032-11f8327c157f.png)

**Comment by ix64** [comment]
很抱歉，由于最近的几次更新中使用了vue的modern构建模式，导致了此问题产生。
现在已经修复，Release已经重新上传。
