### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by farjar** [ix64/unlock-music#40]
我经常从qq音乐下载很多无损，谢谢开发者开发的好用工具，虽然支持批量上传，但是能否实现自动话，功能如下：

1、二进制文件，设置指定监控文件夹，自动解锁，可选歌曲命名格式、是否删除源文件、是否指定保存位置
2、web应用，监控网站根目录下某个文件夹，自动解锁，可选歌曲命名格式、是否删除源文件

**Comment by ix64** [comment]
> 2、web应用，监控网站根目录下某个文件夹，自动解锁，可选歌曲命名格式、是否删除源文件

这个完全不能实现，网页没有访问本地储存的途径

**Comment by ix64** [comment]
> 1、二进制文件，设置指定监控文件夹，自动解锁，可选歌曲命名格式、是否删除源文件、是否指定保存位置

重写正在考虑，等有空正式开始。感谢建议，这些功能将会考虑实现。

**Comment by farjar** [comment]
好的，很期待哦

**Comment by liaozhaishusheng** [comment]
@farjar @ix64 这个功能刚需啊！最近了解到 Mac 平台有 Automator，可能可以实现这个功能。这个可以设置监控文件夹，发现特定扩展名的文件，后面怎么操作就不知道了。

**Comment by ix64** [comment]
即Issue将关闭，此功能转移至 https://github.com/unlock-music/cli/issues/6 进行跟踪
