### ISSUE TITLE
MGG转码OGG上传云盘，IOS手机端无法播放

### ISSUE THREAD

**Issue by K1two2** [ix64/unlock-music#41]
上传到云盘提示转码成功了，测试发现IOS手机端无法播放。
每次都得手动把OGG再转成MP3上传到云盘，请问能够直接解锁为MP3格式，或者其他IOS端支持的格式吗？

**Comment by ix64** [comment]
很抱歉，我们这个工具不涉及重采样，仅仅是进行解锁操作。所有数据都是“按原样”输出。
在此项目中引入转码功能的话，是一件庞大的工程，而且难以达到专业的工具的效果。
因此，建议你使用相关的工具（如ffmpeg, 格式工厂）进行转码。
另：Ogg也是广泛使用、开放的音频格式，您也可以尝试更换播放器。
