### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by denggj28** [ix64/unlock-music#42]
请问是有bug了吗，1.4.0出现了这个问题

**Comment by ix64** [comment]
你好，你使用的浏览器版本和操作系统是什么？

**Comment by denggj28** [comment]
chrome 版本 80.0.3987.149（正式版本） （64 位）
safari 版本13.1 (15609.1.20.111.8)
都是mac平台下的，我也清除了cookie和缓存，但是我不确定是不是清除成功了。

**Comment by ix64** [comment]
好的 我测试一下

**Comment by ix64** [comment]
https://github.com/ix64/unlock-music/releases/tag/1.4.1

**Comment by ix64** [comment]
由于检测GBK编码引发的错误

**Comment by denggj28** [comment]
> https://github.com/ix64/unlock-music/releases/tag/1.4.1

谢谢大佬
