### ISSUE TITLE
希望增加酷我音乐的加密格式解锁

### ISSUE THREAD

**Issue by 2427237507** [ix64/unlock-music#44]
希望增加酷我音乐的加密格式解锁

**Comment by ix64** [comment]
请提供样本，加密格式信息（各种音质对应的扩展名）。

**Comment by ix64** [comment]
需要确认此功能的需求量，有需求的回复或者点个reaction。

**Comment by greatbody** [comment]
[陈奕迅 - 十年.zip](https://github.com/ix64/unlock-music/files/4493230/-.zip)

附件是加密的格式，如果还需要，请提出来。 @ix64

**Comment by 2427237507** [comment]
看错啦，应该是酷我的，我明天吧酷我的加密格式发给你哈



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Rui Sun"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 晚上9:35
收件人: "ix64/unlock-music"<unlock-music@noreply.github.com&gt;; 
抄送: "61534a282bc8d909"<2427237507@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ix64/unlock-music] [调查]希望增加酷我音乐的加密格式解锁 (#44)





 
陈奕迅 - 十年.zip
 
附件是加密的格式，如果还需要，请提出来。 @ix64

**Comment by 2427237507** [comment]
酷我的格式是kwm，在客户端内支持付费转换，详见超大附件


------------------ 原始邮件 ------------------
发件人: "Rui Sun"<notifications@github.com&gt;; 
发送时间: 2020年4月17日(星期五) 晚上9:35
收件人: "ix64/unlock-music"<unlock-music@noreply.github.com&gt;; 
抄送: "61534a282bc8d909"<2427237507@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ix64/unlock-music] [调查]希望增加酷我音乐的加密格式解锁 (#44)





 
陈奕迅 - 十年.zip
 
附件是加密的格式，如果还需要，请提出来。 @ix64
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.

从QQ邮箱发来的超大附件

陈奕迅-十年.kwm (20.45M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=776134318b8fd9cab0d598a14335531b04555506555357051e515050011855500b5019505c5456190b5152090056540551560102653a6187f1bffce0dd18ab9af78b1a5a12586109&t=exs_ftn_download&code=3a41e5a4

**Comment by ix64** [comment]
@greatbody 酷狗已有支持，详见Wiki

**Comment by ix64** [comment]
@2427237507 感谢提供样本。目前kwm文件的分析工作，已取得部分进展。

**Comment by greatbody** [comment]
> @greatbody 酷狗已有支持，详见Wiki

看错了

**Comment by ix64** [comment]
完成了一个已经可用的版本，理论上支持酷我所有的加密文件。
https://tool.ixarea.com/music/download/kuwo/
大家拿去测试一下吧，欢迎反馈。
至于源代码和相关文档，过个把月才有空整理了。

**Comment by ix64** [comment]
https://github.com/ix64/unlock-music/commit/71a8d9fab75dc3475cc370d91004ea374035f390 已增加此功能
