### ISSUE TITLE
酷狗kgm文件无法解密

### ISSUE THREAD

**Issue by lpy-179** [ix64/unlock-music#45]
试了一下，无法解密，在kgm-var-out那个输出文件夹还是原来的那个加密的kgm格式音乐，

**Comment by ix64** [comment]
Alpha-2 Build 2020/04/17已经更新，
主要改进文件类型探测机制和Header长度探测方式。
可以尝试一下使用此版本进行解密。

**Comment by ix64** [comment]
如果仍不成功，请提供相应的样本

**Comment by lpy-179** [comment]
新版本可以，感谢您，github给您点亮一颗星





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MengYX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上11:31
收件人:&nbsp;"ix64/unlock-music"<unlock-music@noreply.github.com&gt;;
抄送:&nbsp;"小生"<2967615343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ix64/unlock-music] 酷狗kgm文件无法解密 (#45)





 
Alpha-2 Build 2020/04/17已经更新，
 主要改进文件类型探测机制和Header长度探测方式。
 可以尝试一下使用此版本进行解密。

**Comment by lpy-179** [comment]
成功了，谢谢您的回复。我会持续关注您的





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"MengYX"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 晚上11:31
收件人:&nbsp;"ix64/unlock-music"<unlock-music@noreply.github.com&gt;;
抄送:&nbsp;"小生"<2967615343@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ix64/unlock-music] 酷狗kgm文件无法解密 (#45)





 
如果仍不成功，请提供相应的样本
