### ISSUE TITLE
无法解锁的mgg一枚

### ISSUE THREAD

**Issue by 2427237507** [ix64/unlock-music#47]
https://www.lanzous.com/iborfsf

**Comment by ix64** [comment]
感谢提供样本，改善mgg/mflac解锁方式已在计划列表中。

**Comment by ix64** [comment]
Release 1.5.1 已针对mgg文件进行算法改进，确认此文件可以成功解密。
详见 https://github.com/ix64/unlock-music/commit/e7b86a47790973012cc7391a60e595486348b054
https://github.com/ix64/unlock-music/releases/tag/1.5.1
