### ISSUE TITLE
关于反向加密

### ISSUE THREAD

**Issue by fakedestinyck** [ix64/unlock-music#48]
作者您好，首先很感谢能为我们带来这个软件！真的很有用！
然后这里有一个小小的 可能有些奇怪的需求 不知道作者能不能实现
就是比如我想传音乐到qq微云网盘，但是mac上并不能上传的qq微云网盘，而从手机上似乎只能读取**加密过**的微云网盘文件，所以想问问作者，不知道能不能实现反向的加密（这样的话，直接通过网页版微云上传文件，就可以在手机上直接读取到**加密过后**的音乐）
再次感谢！

**Comment by ix64** [comment]
此功能将在 Golang 版本中考虑实现。
但按常理加密后的文件，应该不能上传云盘并播放。

**Comment by fakedestinyck** [comment]
> 此功能将在 Golang 版本中考虑实现。

啊好 辛苦了！
> 但按常理加密后的文件，应该不能上传云盘并播放。

害我也不知道，我只是实在没法上传 就 只是有个这样的猜想 也不知道可不可行

**Comment by github-h** [comment]
经过测试 

使用Win下的QQ音乐**客户端**将本地的**FLAC**文件上传至微云音乐云盘（**无版权限制的音乐**）
![图片](https://user-images.githubusercontent.com/49114731/89739419-24d28900-dab3-11ea-9e00-4475b2ac7855.png)

微云中会生成后缀名为**.666c616c**的文件
![图片](https://user-images.githubusercontent.com/49114731/89739431-374cc280-dab3-11ea-99b7-aeaeb0ab82f5.png)

将文件下载至本地进行对比，hash值并不一样。说明改文件在客户端上传时经过了加密
![图片](https://user-images.githubusercontent.com/49114731/89739478-8e529780-dab3-11ea-954d-46478d13ceb9.png)

将后缀名改为**.qmcflac**格式后上传至[解密网站](http://moresound.tk/music/tool/)，下回本地后，对比Hash，发现一致。

由此得出通过客户端上传音乐文件至微云后的加密文件，都可采用[解密网站](http://moresound.tk/music/tool/)进行文件还原
需要注意的是在客户端内下载微云文件，客户端会自动解密文件至正常格式

**Comment by github-h** [comment]
若本Issue得到解决，即反向加密功能实现

也就是可以将普通**FLAC**文件加密成**qmcflac**，通过修改后缀名，上传至微云云盘目录，达到绕过版权限制的目的

先说结论，此方法不可能实现。虽然微云云盘中出现了文件，但客户端中的音乐网盘并不会有歌曲信息

版权限制的歌曲，在购买专辑或购买单曲后取消了上传限制。直接通过客户端即可正常上传FLAC文件至微云云盘

**总的说一点，如果想让微云音乐网盘正常显示音乐文件，必须通过官方客户端（手机/电脑）才可行，直接上传文件至微云，音乐网盘的歌单中并不会出现歌曲信息**

**Comment by ix64** [comment]
即Issue将关闭，此功能转移至 https://github.com/unlock-music/cli/issues/7 进行跟踪
