### ISSUE TITLE
GitHub已被DNS污染

### ISSUE THREAD

**Issue by pjjailyh** [ix64/unlock-music#49]
如题，GitHub已被污染所以首次打开要翻墙，由于本人未学过Web前端布置，是否考虑打包一个安卓本地文件呢？（安卓目前只有典型的几种加密，主要是酷狗和酷我的加密没有安卓版）
（当然，这样也有一点好处，就是对应公司的法务很可能不会再发律师函）

**Comment by pjjailyh** [comment]
我已本地部署成功，感谢。
不过，第一次打开的检测更新有点麻烦，首次会较慢。
联网部署我会自学。
此issue我暂不关闭，算是提个建议，看完直接关闭就好，感谢您。

**Comment by ix64** [comment]
你好，暂时没有开发手机版的计划。我本身没有任何Android的开发经验，如果有兴趣你可以自行实现。其实这个做这个项目本来只是自用，放在此处看大家缘分吧 :upside_down_face:
