### ISSUE TITLE
有没有命令行版的

### ISSUE THREAD

**Issue by recall704** [ix64/unlock-music#5]
我觉得更好的方式是把当前目录下的音乐自动转换，而不是要先打开一个网页。

**Comment by ix64** [comment]
这个项目的出发点就是：软件先下载/安装，才能运行过程比较麻烦，特别对于移动设备。
另外带有GUI的软件工程量大，无GUI的对于普通用户不友好，因此选择了Web应用。

**Comment by ix64** [comment]
项目是为方便个人学习、欣赏音乐创建的，一般来说，转换需求不会特别大。
有极大批量转换需求的，可以考虑将本项目转换成Node.js版本，或者其他语言重写。
最近比较忙，应该没有时间做这个。
