### ISSUE TITLE
[QQ 音乐]不能解锁 QQ 音乐 UWP 版缓存的音乐

### ISSUE THREAD

**Issue by xymopen** [ix64/unlock-music#50]
QQ 音乐 UWP 版的边听边存功能会将音乐保存在 `%LocalAppData%\Packages\903DB504.QQWP_a99ra4d2cbcxa\TempState\QQMusicCache` 中。这些文件没有后缀名。

使用二进制编辑器打开时发现文件头与标准 `.qmc0` 不同：

![屏幕截图](https://user-images.githubusercontent.com/8053733/80083786-9203f200-8588-11ea-9fae-56225f279f75.png)

将文件头清零，并手动添加后缀名后可以正常解锁。

[样例](https://github.com/ix64/unlock-music/files/4521577/002004003dd7JJ3xx6CC9hh5333XX2HH4WW3jj7AA30.zip)

**Comment by ix64** [comment]
感谢提供信息。如果需要实现这个功能，我们还需要确认更多客户端和更多缓存文件，来确认其识别模式。但我最近时间比较少，目前预计将与CLI版本完成后考虑实现。如果你能进行这项工作的话，这将可以加快其进展。

**Comment by ix64** [comment]
抱歉，经过考虑，此类缓存文件不属于正规途径获取的源文件。在项目中添加此类文件的破解法律风险过大，因此最终决定目前不添加缓存文件的破解。
本人不赞成此类非合规方式获取源文件。仍然建议开通相关软件的会员资格，使用软件提供的下载功能来获得这音乐源文件。
