### ISSUE TITLE
[QQ音乐]无法解密QQ音乐缓存

### ISSUE THREAD

**Issue by dragon-archer** [ix64/unlock-music#52]
将QQMusicCache文件夹中的文件改后缀名后无法解密（mflac,ogg,mgg,flac格式均如此）
以下为一个我通过文件大小匹配到的音乐文件（我通过QQ音乐的下载功能下载了同一首音乐，原始文件名已保留，但去除了缓存文件的cache后缀名）
由于GitHub文件大小和文件格式的限制已经文件分割
[QQMusic-flac.001.tar.gz](https://github.com/ix64/unlock-music/files/4542756/QQMusic-flac.001.tar.gz)
[QQMusic-flac.002.tar.gz](https://github.com/ix64/unlock-music/files/4542757/QQMusic-flac.002.tar.gz)
[QQMusic-flac.003.tar.gz](https://github.com/ix64/unlock-music/files/4542758/QQMusic-flac.003.tar.gz)

附：Windows 10 19613 Insider Preview
QQ音乐 17.52 标准版（非UWP）

**Comment by ix64** [comment]
经验证，Windows版 Cache文件虽然使用相似的方案来对缓存文件加密。但是其密钥并非固定，且储存于本地的数据库中，并非和音乐文件一同提供。因此，我们的工具将不考虑支持此类文件。
另外，本人不赞成此类非合规方式获取源文件。仍然建议开通相关软件的会员资格，使用软件提供的下载功能获得这些文件。

**Comment by dragon-archer** [comment]
好吧，其实我本身也有QQ音乐会员，只是想验证一下
另外，据我观察，密钥可能存储于QQMusicCache目录下的QQMusicLyricNew文件夹中

**Comment by ix64** [comment]
> 另外，据我观察，密钥可能存储于QQMusicCache目录下的QQMusicLyricNew文件夹中
应该不是，这个文件夹存放的是歌词文件。
据我观察，可能位于%AppData%\Tencent\QQMusic\qmlist64.db 这个加密的数据库文件中。
