### ISSUE TITLE
关于vpr格式音乐文件解密的申请

### ISSUE THREAD

**Issue by 2841889196** [ix64/unlock-music#53]
首先，谢谢大佬的创作。我在使用您的成果过程中，发现只能解密80m的歌曲，浏览上述记录后才知道可能是大佬的样本不够。因此，我想提供几十g的vpr样本，其中绝大多数是100m以上的，望大佬早日做出较完美的产品。谢谢。
链接：https://pan.baidu.com/s/1RBlkeJm9CCZWENfdgIK5_Q 
提取码：kh9h
另外，虽然像你这样的大佬都不缺钱，但我仍想打赏100元，表达心意，这是我的微信号17718131068，如果做出来了，请加我微信，我发个红包，虽然大佬都不缺钱，但这是心意。

**Comment by ix64** [comment]
你好，很感谢你的心意。虽然心动，但是我本人不打算因此项目接受赞助和打赏。毕竟前段时间PanDownload的事情也让让人兔死狐悲。这个项目毕竟也是会动某些人奶酪的，再有资金往来，到时候便都说不清了。
嗯，kgm/vpr的解密已在日程上，目前样本是相对充足的。主要是最近忙于学习考试，没办法投注太多精力于此项目，有空我将继续进行相关分析。
此外，你提供的链接已无法打开。

**Comment by 2841889196** [comment]
链接：https://pan.baidu.com/s/1RBlkeJm9CCZWENfdgIK5_Q 
提取码：kh9h

**Comment by 2841889196** [comment]
不接受打赏，那我怎么才能回报你，这真的帮了我很大的忙，毕竟这个软件vip每个月要25元，早就不想续费了。所以很想回报你。

**Comment by 2841889196** [comment]
链接已更新。

**Comment by ix64** [comment]
刚刚想到一个可能可以的方案。可以提供几个你遇见过最大的vpr文件的歌曲、歌手信息吗？

**Comment by 2841889196** [comment]
好的，最大的等下

**Comment by 2841889196** [comment]
链接：https://pan.baidu.com/s/1A__nfRznRO1Th1v4nvyWOg 
提取码：br8t
这个是最大的格式为dsd的vpr文件

**Comment by 2841889196** [comment]
链接：https://pan.baidu.com/s/16eEvKUlntxOS4VAphAeyeg 
提取码：wna0
这个是flac24bit格式的最大文件

**Comment by 2841889196** [comment]
大佬，用你这个软件解密的音乐存在一个问题，是一个共性的问题，用别的软件解密qq音乐和虾米灯具有私密格式的音乐都存在的问题。
就是解密高质量音乐——24bit及以上的音乐，在车机上放会有很大的噪音，等下我录下来，链接给你，你听听。
我觉得是解密过程中添加了一些不和谐的信息，影响了音谱整体性。瞎猜的，别介意。

**Comment by ix64** [comment]
> 我觉得是解密过程中添加了一些不和谐的信息，影响了音谱整体性。瞎猜的，别介意。

应该和解密过程无关，解密过程是完全是将这些文件当作二进制数据处理的，而非音频数据。
如果是解密不正确一般会导致完全无法播放。而且这些文件使用的算法都是一样的，不应该存在某些可以而某些不行的情况。
你尝试使用其他设备试试是否依然存在此类情况？

**Comment by 2841889196** [comment]
链接：https://pan.baidu.com/s/1c9ZNGiQ3voJB5OzD3zB-Yg 
提取码：zzvc
遇到的噪音问题

**Comment by 2841889196** [comment]
其他设备就没遇到

**Comment by ix64** [comment]
Alpha-3 Build 2020/05/03 版本已更新，支持220MB以下文件解锁。
[https://github.com/ix64/unlock-music/wiki/其他音乐格式工具#酷狗音乐-kgmvpr解锁工具](https://github.com/ix64/unlock-music/wiki/%E5%85%B6%E4%BB%96%E9%9F%B3%E4%B9%90%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%85%B7#%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90-kgmvpr%E8%A7%A3%E9%94%81%E5%B7%A5%E5%85%B7)

**Comment by ix64** [comment]
如果有比220MB更大的文件，欢迎提供相应的歌曲、歌手信息。

**Comment by 2841889196** [comment]
大佬，你怎么这么厉害。你不要红包让我很为难啊，要不我在天猫上给你买两箱莫斯利安发过去，不然我感觉内心空荡荡的。

**Comment by ix64** [comment]
已经感受到了你的认可和好意，我真的很开心。认可和欣赏，就是我在这个项目上所希望获得的全部了。
如果你希望帮助这个项目，那就将它分享给更多人，让更多人欣赏音乐时能够获得更好体验吧！😄
