### ISSUE TITLE
希望支持解锁m4p格式的音乐

### ISSUE THREAD

**Issue by hmsjy2017** [ix64/unlock-music#55]
iTunes(Apple Music)下载下来的音乐是加密的m4p格式，只能使用iTunes播放，希望支持解锁。

**Comment by ix64** [comment]
了解到，貌似现在的iTunes音乐文件是不含DRM的。
可以前往 https://support.apple.com/zh-cn/HT204310 了解一下。

**Comment by ix64** [comment]
如果确实进行了加密，请提供相应的信息和一定量的样本文件。

**Comment by bookyue** [comment]
部分正确，从Apple Music下载的音乐的确是加密的，格式为m4p，使用FairPlay DRM加密。
而且无法通过iTunes进行转换（转换成无保护的音乐文件格式）。
![image](https://user-images.githubusercontent.com/23428080/84016475-e97ee580-a9af-11ea-98c7-787791848947.png)
但是iTunes Plus可以下载DRM-free music。
也就是说，Apple Music订阅的用户下载的歌曲有DRM Protection，而在iTunes里购买的音乐没有。
参考链接：
* [Is It Legal to Remove DRM from Apple Music?](https://medium.com/@jovanabb/is-it-legal-to-remove-drm-from-apple-music-5df8442ba4c3)
* [How to Remove DRM From Apple Music?](https://www.tunefab.com/tutorials/apple-music-drm--removal.html)
* [iTunes Store](https://zh.wikipedia.org/wiki/ITunes_Store)

附上一首黄老板的Photograph(m4p)
[06 Photograph.tar.gz](https://github.com/ix64/unlock-music/files/4745234/06.Photograph.tar.gz)

**Comment by ix64** [comment]
很抱歉，经过粗略查询，了解到：
1. iTunes的音乐加密使用DRM技术，密钥未包含于文件之内，因此无法如同其他几个音乐软件一样，通过算法解锁。
2. 你所提供的链接中使用的软件是通过内录的办法移除DRM，且必须配合iTunes软件。
因此，决定不对iTunes(m4p)增加支持

此Issue将关闭
