### ISSUE TITLE
网易云音乐会被洗掉 tag 元信息

### ISSUE THREAD

**Issue by Phishion** [ix64/unlock-music#56]
整理的时候非常麻烦，因为连基础的序号都没有，这个是网易的音乐本来就没有元信息的原因，还是解码的过程被洗掉了？

**Comment by ix64** [comment]
解锁出来的文件本身不包含meta信息，下载时已被网易云清除。对于mp3文件，此项目添加了写入id3信息的功能

**Comment by Phishion** [comment]
谢谢回复，谢谢！
