### ISSUE TITLE
无法解锁的mflac，不知道和上一个issue里的加密方式一样不一样

### ISSUE THREAD

**Issue by Zhanglv0413** [ix64/unlock-music#57]
win10 1909
QQ音乐 3.11.0
以下几首歌曲无法成功解码，由于是vip所以直接提供文件
链接：https://pan.baidu.com/s/1gppJbS2ODC1c4n0bQSrZqQ
提取码：a4hb

**Comment by ix64** [comment]
经确认，确实与 #52 中提到的问题一致
此Issue将关闭，内容将复制到 #52 中
