### ISSUE TITLE
网易云有一个无法解锁的ncm文件

### ISSUE THREAD

**Issue by 503392857** [ix64/unlock-music#58]
[dvsn Popcaan - So What (feat. Popcaan).zip](https://github.com/ix64/unlock-music/files/4627138/dvsn.Popcaan.-.So.What.feat.Popcaan.zip)

**Comment by 503392857** [comment]
win10
网易云2.7.1
unlock-music 1.5.1和1.3.4都无法解锁

**Comment by ix64** [comment]
此问题是由于该音乐不含封面图片信息引起。https://github.com/ix64/unlock-music/commit/7b9070f99d875db1b89e6a9f165ad117ada1bba8 中已修复。

**Comment by ix64** [comment]
下一次Release中将会包含该项修复。
如果急需使用，可以自行构建或者下载[Snapshot-112](https://tool.ixarea.com/music/download/web-build/112/)
