### ISSUE TITLE
下载完源代码，用谷歌或者火狐浏览器打开一直转圈

### ISSUE THREAD

**Issue by jingxiangAdmin** [ix64/unlock-music#60]
![image](https://user-images.githubusercontent.com/59500847/82135995-7f08d880-983b-11ea-8fab-df477d17f5ae.png)

**Comment by jingxiangAdmin** [comment]
打开    public   index.html文件 之后就这样子   浏览器是最新版本的

**Comment by ix64** [comment]
使用前请查看README文档！提Issue前请搜索是都有相同Issue！

## 使用已构建版本
- 从[GitHub Release](https://github.com/ix64/unlock-music/releases/latest)下载已构建的版本
- 解压缩后即可部署或本地使用（**请勿直接运行源代码**）

**Comment by jingxiangAdmin** [comment]
点legacy.tar.gz
这个也是在转圈啊，能私发我一份吗？
