### ISSUE TITLE
是否可以增加自动对flac添加专辑封面的功能

### ISSUE THREAD

**Issue by wfsg00098** [ix64/unlock-music#61]
从网易云音乐下载的ncm，解密完毕后为mp3的可以自动添加封面，为flac的没有专辑封面

请问可否添加一下这个功能。

非常感谢大佬的工具，辛苦了！

样本地址：https://www.guaiqihen.com/ncm/下山.ncm
此ncm文件解密完毕后为flac

**Comment by ix64** [comment]
由于js无比较好用的flac写入meta的库，此功能将于未来的cli版本中添加

**Comment by wfsg00098** [comment]
好的，谢谢！
