### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by dragon-archer** [ix64/unlock-music#64]
https://github.com/ix64/unlock-music/blob/a140b45e5fc8ffc19a9dd338b091a519d884e745/.drone.yml#L22

此处应为`modern`而非`morden`

**Comment by dragon-archer** [comment]
https://github.com/ix64/unlock-music/blob/a140b45e5fc8ffc19a9dd338b091a519d884e745/.drone.yml#L30
此行也是

**Comment by ix64** [comment]
此问题与 #62 重复
且在 https://github.com/ix64/unlock-music/commit/ecff3d34b0ac4f2b6d5f70cd148ffe81a8a72e90 中已修复此问题
请查看最新版本的源代码，感谢你的指出
