### ISSUE TITLE
vpr解密后达不到22kHz

### ISSUE THREAD

**Issue by David-H-1** [ix64/unlock-music#65]
我加入了一个dsd无损音乐交流群，群友用频谱分析了解密后的dff文件，发现连22kHz都达不到。请尽快改善软件算法！针对viper的！！！

**Comment by David-H-1** [comment]
![72b9da1dcb87930b](https://user-images.githubusercontent.com/60801469/82719147-b3472380-9c97-11ea-9414-ed58e3003747.png)

解密前后比较zip：https://drive.google.com/open?id=1QVXxQgvgEjyDisdxjT-BIWfPf9kJiOXq

**Comment by ix64** [comment]
此项目的解锁操作不涉及任何的重采样，所有数据都是“按原样”提供。因此，任何音质问题都与此项目无关。

**Comment by ix64** [comment]
另，请注意你的说话方式。提出Issue时请不要使用要求性的语气！

**Comment by ix64** [comment]
此问题请联系酷狗。

**Comment by David-H-1** [comment]
那就非常抱歉麻烦您了。是我的错。

**Comment by David-H-1** [comment]
网上有很多这样假无损的，表面上是dsd，实际只有CD音质

**Comment by David-H-1** [comment]
我再也不相信酷狗了，真正的母带一般只有录音室才有

**Comment by David-H-1** [comment]
> 此问题请联系酷狗。

联系酷狗？那不是往枪口上撞吗？！酷狗是腾讯旗下的，人家也不是吃素的，肯定会改变加密算法的！

**Comment by David-H-1** [comment]
> 此问题请联系酷狗。

再说了，酷狗和腾讯一样没有一个# 人工客服，答复的全是机器人
