### ISSUE TITLE
手机版Chrome浏览器兼容有点问题

### ISSUE THREAD

**Issue by MrTaner1993** [ix64/unlock-music#66]
手机版Chrome浏览器兼容有点问题，打开一直转圈，我手机是MI 10用自带的浏览器就没问题
[Screenrecorder-2020-05-23-19-04-13-595.zip](https://github.com/ix64/unlock-music/files/4671669/Screenrecorder-2020-05-23-19-04-13-595.zip)

**Comment by ix64** [comment]
这与此程序无关，应该是文件系统的问题。可以尝试部署于Web服务器上或者使用由第三方提供的在线部署。

**Comment by ix64** [comment]
使用内置浏览器时使用的是 file:// 协议，使用 Chrome 时使用的的时 content:// 协议，导致此问题出现
