### ISSUE TITLE
[调查]增加其他沟通方式

### ISSUE THREAD

**Issue by ix64** [ix64/unlock-music#67]
最近收到许多Email，有不少是软件使用上的问题、软件功能上的疑问等。此类问题的讨论不适合通过GitHub Issue进行，此处处理的问题应该是和软件设计直接相关的。

因此有建议创建并使用其他交流渠道的，因此希望在此处进行一项小调查，大家对于创建其他交流渠道的建议如何？

有更多想法的、可以通过Commet一起讨论一下！谢谢大家

(由于gh-polls无法更新选项，还是通过Reaction来进行吧）

**Comment by wfsg00098** [comment]
不是很建议通过别的渠道交流，可能会存在“内鬼”

**Comment by EmmmMonster** [comment]
我认为不应该使用即时聊天软件。建议维护论坛。
聊天群对解决问题不友好。论坛能够沉淀有价值的提问、回答。

**Comment by ix64** [comment]
> 不是很建议通过别的渠道交流，可能会存在“内鬼”

这些交流本来都是公开的，大概也没有什么值得或者说需要“内鬼”才能获取的吧？

**Comment by ix64** [comment]
> 我认为不应该使用即时聊天软件。建议维护论坛。
> 聊天群对解决问题不友好。论坛能够沉淀有价值的提问、回答。

忽然觉得也是，此类交流通过论坛，按问题区分可以避免无意义的重复

**Comment by wfsg00098** [comment]
> > 不是很建议通过别的渠道交流，可能会存在“内鬼”
> 
> 这些交流本来都是公开的，大概也没有什么值得或者说需要“内鬼”才能获取的吧？

我不知道本项目会不会被音乐APP官方干涉，担心会出现这种情况

**Comment by yourmother233** [comment]
照腾讯的吃相还是不要在qq上搞

**Comment by David-H-1** [comment]
强烈反对增加沟通方式，因为很有可能被音乐平台的人员发现，尤其是腾讯的
他已经改过加密格式了

**Comment by David-H-1** [comment]
即使要搞也绝不能再腾讯旗下的平台建群

**Comment by Kerinlin** [comment]
> 我认为不应该使用即时聊天软件。建议维护论坛。
> 聊天群对解决问题不友好。论坛能够沉淀有价值的提问、回答。

赞同，可在github上寻找个可套用的论坛模板试试

**Comment by changsen-dev** [comment]
作为已经使用几年的telegram用户来说，用电报吧

**Comment by 17huiwei** [comment]
> 作为已经使用几年的telegram用户来说，用电报吧

嗯，我也赞成，既然能上github，也可以顺畅使用电报。至于有没有内鬼，我觉得哪里都有内鬼。只要不违反政治，不谈敏感话题，都可以的。

不过IM是作为一个补充，而不是替代github存在，所以两者的功能要区分开。前者是为了大家交流，可以交流这个软件，也可以交流音乐，电报里就有不少音乐分享群，其中有很多都是类似软件的群，最后演变成了音乐分享，每天都有朋友分享好听的音乐，所以很活跃。

希望能尽快找到栖身地，多谢啦。

**Comment by SaltedFish-Extreme** [comment]
电报还有官方的监控群呢，互联网上没有绝对的隐私，只要不是自己的平台都不可信，非得找个交流的平台不如自己服务器搭建个交流平台🙃

**Comment by changsen-dev** [comment]
> 电报还有官方的监控群呢，互联网上没有绝对的隐私，只要不是自己的平台都不可信，非得找个交流的平台不如自己服务器搭建个交流平台🙃

我说你咋这么杠的呢，既然是用别人的，就肯定都会有，就看别人想不想这样做了，反正我是觉得只要不被大陆政府数据监控就行，国外监控就算有数据他能奈我何？国内就不一样了，他真就奈我何

**Comment by SaltedFish-Extreme** [comment]
> > 电报还有官方的监控群呢，互联网上没有绝对的隐私，只要不是自己的平台都不可信，非得找个交流的平台不如自己服务器搭建个交流平台🙃
> 
> 我说你咋这么杠的呢，既然是用别人的，就肯定都会有，就看别人想不想这样做了，反正我是觉得只要不被大陆政府数据监控就行，国外监控就算有数据他能奈我何？国内就不一样了，他真就奈我何

现在说事实也算杠了吗🤨你流量从哪流到哪别人能不知道吗，要不也不会有那么多送温暖的了🤔既然都不安全，就安安心心的用最方便的交流工具或者就安于现状好了🙃记得github有个即时通讯的平台不是？总比国内软件不用非得翻墙用别的不见得就安全的要好的多🧐

**Comment by changsen-dev** [comment]
那你就gun回原始社会去吧，那里最安全

咸鱼至尊 <notifications@github.com> 于2020年7月4日周六 下午11:58写道：

**Comment by ix64** [comment]
感谢大家的建议，在此谢过了。不过 @changsen-dev 还是不要言辞过激，希望大家友好交流。

很抱歉，这一个月以来忙着别的事情，暂时无暇顾及此项目。
我预计一个星期之后会继续回到此项目的开发之中，届时会继续处理此问题。

**Comment by genema** [comment]
建议拉一个potato 群

**Comment by ix64** [comment]
感谢大家的建议。
根据大家的讨论内容，最终决定使用Telegram作为额外的交流渠道。
但GitHub Issue将仍作为项目的主要交流渠道，与项目改进直接相关的，仍会在此进行。
Telegram将更多用于不适宜在GitHub Issue进行的讨论，如寻求软件使用帮助、与项目改进无直接关联的讨论等。

**Comment by ix64** [comment]
新建了一个 Telegram群组 ：https://t.me/unlock_music_chat 
我也是第一次尝试此类工作，希望大家海涵。
对于Telegram群组的运作有任何建议的，可以在此处告知我，感谢大家
