### ISSUE TITLE
[QQMusic] 无法解锁的文件样本

### ISSUE THREAD

**Issue by hxm108** [ix64/unlock-music#69]
[mflac样本.zip](https://github.com/ix64/unlock-music/files/4774566/mflac.zip)

**Comment by hxm108** [comment]
[mgg样本.zip](https://github.com/ix64/unlock-music/files/4774568/mgg.zip)

**Comment by ix64** [comment]
此文件的问题与 #51 中的一致，此Issue将关闭，请关注#51 。
打开Issue前，请对照 [使用提示](https://github.com/ix64/unlock-music/wiki/%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA#%E5%85%B3%E4%BA%8Eqq%E9%9F%B3%E4%B9%90mflacmgg%E6%A0%BC%E5%BC%8F) 页面，确认是否已有相关信息
