### ISSUE TITLE
希望增加华为自带音乐app的加密格式的破解

### ISSUE THREAD

**Issue by David-H-1** [ix64/unlock-music#70]
鄙人用的机型是华为mate 20，结果发现很多自带音乐软件里的歌曲，即使订阅了会员，下载出来的也是专属加密格式，只有华为自带的播放器能播放，其他app及电脑均无法正常打开。
在此，鄙人特提出一个feature request
就是烦请您增加一个华为音乐的解密模块
但是因为鄙人在海外，没有回国VPN是购买不了会员，因此下载不了的
所以麻烦您开发一下相关的解密模块，以造福华为手机用户
非常感谢！

另附：因为贵方未开发手机app，所以让用户自行导入到电脑上解密亦可。

愿贵方的项目越来越完善！

**Comment by ix64** [comment]
你好，请提供相应的样本文件或者可验证的解密方案或第三方工具。
我本人亦无任何华为设备。

**Comment by ix64** [comment]
此Issue将关闭，直至确实有更多用户拥有此需求并能提供相应信息。
