### ISSUE TITLE
解锁完的文件没有封面，解锁之前能看到，这个可以帮忙看一下吗？

### ISSUE THREAD

**Issue by jasonge26** [ix64/unlock-music#71]

**Comment by teruspot** [comment]
下载一个MP3tap，其实很多歌曲的封面都是不清晰的，自己网上找图再添加比较好

**Comment by ix64** [comment]
[v1.6.0](https://github.com/ix64/unlock-music/releases/tag/v1.6.0)版本中，已解决此问题
