### ISSUE TITLE
关于封面获取问题

### ISSUE THREAD

**Issue by hxm108** [ix64/unlock-music#75]
在您更新的新版本中，您将封面的获取调转到您的服务器api上进行获取
但是在无网络情况下就无法加载封面哦

**Comment by hxm108** [comment]
建议最好还是从文件上获取封面信息吧

**Comment by ix64** [comment]
文件本身不包含封面

**Comment by hxm108** [comment]
> 文件本身不包含封面

加密格式的音乐不包含封面信息吗？

**Comment by ix64** [comment]
从腾讯和网易下载的音乐文件本身不包含任何封面图像。
网易的Meta数据中包含有相应的链接。QQ音乐的则无任何信息。

**Comment by hxm108** [comment]
> 从腾讯和网易下载的音乐文件本身不包含任何封面图像。
> 网易的Meta数据中包含有相应的链接。QQ音乐的则无任何信息。

感谢！

**Comment by ix64** [comment]
此次更新内容主要是解决腾讯的服务器有CORS限制的问题

**Comment by ix64** [comment]
算是临时方案，从我的服务器进行中转。很快当CLI版本完成之后将移除此更改。

**Comment by hxm108** [comment]
![image](https://user-images.githubusercontent.com/51278893/87855791-2645e100-c94d-11ea-9b77-4344177ebe2c.png)
QQ音乐下载的封面仅非加密格式音乐有效？

**Comment by hxm108** [comment]
> 算是临时方案，从我的服务器进行中转。很快当CLI版本完成之后将移除此更改。

CLI版本发表后将停止对Web端的更新吗？

**Comment by ix64** [comment]
> QQ音乐下载的封面仅非加密格式音乐有效？
是的

**Comment by hxm108** [comment]
> > QQ音乐下载的封面仅非加密格式音乐有效？
> > 是的

感谢！

**Comment by ix64** [comment]
> CLI版本发表后将停止对Web端的更新吗？

预计不会，Web版本能使用的功能都会继续添加上去

**Comment by hxm108** [comment]
> > CLI版本发表后将停止对Web端的更新吗？
> 
> 预计不会，Web版本能使用的功能都会继续添加上去

感谢您继续对该项目提供支持！
