### ISSUE TITLE
“立即保存”功能未告知路径

### ISSUE THREAD

**Issue by woooodbond** [ix64/unlock-music#76]
# “立即保存”功能未告知路径

## 问题描述

勾选“立即保存”，页面没有提示保存路径是什么，也没有让用户自行选择保存路径的功能，希望修复。

此外，希望能添加“打包下载”功能，多个文件打包成一个文件（tar、zip等）。

## 环境

- Windows 10 1909
- Microsoft Edge 44.18362.449.0

## 真的感谢作者的这项工作！！！

**Comment by ix64** [comment]
你好。
保存路径由浏览器来决定的，此工具运行于浏览器内，与文件系统无任何接触。此后会考虑增加提示。
需保存的文件直接位于内存中，打包保存会消耗大量CPU，切无法达到减少内存占用的目的，因此暂不考虑支持
