### ISSUE TITLE
1.6.0 版本解锁 .ncm 格式文件时出现标签重复写入的问题

### ISSUE THREAD

**Issue by Fwagan** [ix64/unlock-music#77]
可以稳定复现，结果如图
![image](https://user-images.githubusercontent.com/49264109/88380612-71417780-cdd7-11ea-9ca6-205f80b3a880.png)

FB2K 和 Mp3tag 内显示均不正常，但是通过 Windows 资源管理器查看 Details 时显示正常

未测试其他格式

环境
Windows 10 1809
Chrome 84.0.4147.89

**Comment by ix64** [comment]
你好，请提供一下样本文件来进行分析

**Comment by Fwagan** [comment]
链接: https://pan.baidu.com/s/1HgMghhpTVx777okzud_3qQ 
提取码: z8pw

忘记提了，是从网易云UWP版本客户端 1.4.1 下载的，网易云现在似乎已经不再提供新的UWP版本客户端了，可能是和旧客户端有关？

**Comment by ix64** [comment]
此问题确实存在。网易云对于flac格式的文件，似乎没有像mp3格式的一样抹除Metadata

**Comment by ix64** [comment]
1.6.0版本在写入flac封面图片时，再次写入了Meta信息，导致重复
