### ISSUE TITLE
解锁后没有metadata

### ISSUE THREAD

**Issue by David-H-1** [ix64/unlock-music#79]
在fb2k和资源管理器上都看不到
原ncm文件从手机客户端下载解锁后metadata全都没有了![IMG_20200802_113106.jpg](https://user-images.githubusercontent.com/60801469/89129672-9b3d1d00-d4ee-11ea-8a46-e027160e57d0.jpg)[]()![IMG_20200802_113148.jpg](https://user-images.githubusercontent.com/60801469/89129674-9d06e080-d4ee-11ea-8ec0-62c52880b4ef.jpg)![IMG_20200802_113210.jpg](https://user-images.githubusercontent.com/60801469/89129675-9e380d80-d4ee-11ea-9bb6-a602ef74ac44.jpg)

我的网络正常
用的网页版在线解锁的
作者和专辑在fb2k中均显示问号

**Comment by David-H-1** [comment]
部分歌曲有metadata，但大多数例如avicii的歌解锁后metadata就消失了

**Comment by David-H-1** [comment]
另外当作者人名中含有类似ó é ê ú ǔ这类的时候，metadata中那个字符就会变成乱码

**Comment by ix64** [comment]
你好，请提供相应的样本以供进一步的分析
