### ISSUE TITLE
可以不用考虑多语言支持

### ISSUE THREAD

**Issue by KyleBing** [ix64/unlock-music#8]
看到 checklist 里有个 多语言支持。
个人感觉可以不用考虑多语言支持，因为本身项目的目标就是网易云和QQ用户，会用这两个软件的用户都会中文 😂

**Comment by ix64** [comment]
有道理。固有印象，发GitHub的要加英文支持，哈哈。

**Comment by KyleBing** [comment]
真的是太感谢你这个项目了，之前下载音乐一下到 `ncm` 的就很无奈，现在瞬间感觉捡了一个亿。大赞！为人民服务。
整的我都想给这个项目捐款了，块儿八毛也是心意。

**Comment by ix64** [comment]
前些天已经收到TX法务的警告:cry: 我本人未来应该不会对这个项目进行太多功能上的更新了，捐款就不必了。
