### ISSUE TITLE
在解锁Q音新歌时报错

### ISSUE THREAD

**Issue by zerosherd** [ix64/unlock-music#80]
样本链接：https://cloud.189.cn/t/6zq6v2qyMvAn
报错提示：已测试旧歌正常
![image](https://user-images.githubusercontent.com/45382820/89489096-4514f600-d7dc-11ea-8a3a-49b4bda19623.png)

**Comment by ix64** [comment]
请使用其他无需登录即可下载的传输方式。

**Comment by ix64** [comment]
另 请检查是否与 [Wiki](https://github.com/ix64/unlock-music/wiki/%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA#%E5%85%B3%E4%BA%8Eqq%E9%9F%B3%E4%B9%90mflacmgg%E6%A0%BC%E5%BC%8F) 或 https://github.com/ix64/unlock-music/issues/51 中所提及的一致

**Comment by zerosherd** [comment]
已上传蓝奏云：https://zerosherd.lanzous.com/iW8d8fcgc1g
下载后请改格式为mgg格式，另已确定和#51提及不同，旧版本此歌解码同样出错，但由于某些原因，只能在本人电脑测试，可能有微小概率为系统原因。

**Comment by ix64** [comment]
![image](https://user-images.githubusercontent.com/13902388/89496482-0176b800-d7ed-11ea-83ab-d3e4800a4281.png)

> 已上传蓝奏云：https://zerosherd.lanzous.com/iW8d8fcgc1g

这里下载到的文件，确实与 #51 所提及的一致。
