### ISSUE TITLE
编译时出现错误

### ISSUE THREAD

**Issue by Unknow-404** [ix64/unlock-music#82]
日志文件：[debug.log](https://github.com/ix64/unlock-music/files/5037039/debug.log)

**Comment by ix64** [comment]
大概率与程序本身无关，建议清空node_modules重试。项目使用CI，每一版本都是能够自动编译成功的。

--------------原始邮件--------------
发件人："Unk№w "<notifications@github.com&gt;;
发送时间：2020年8月7日(星期五) 凌晨2:04
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ix64/unlock-music] 编译时出现错误 (#82)
-----------------------------------

 

 
日志文件：debug.log

**Comment by ix64** [comment]
参见 https://ci.ixarea.com/ix64/unlock-music 以及 https://github.com/ix64/unlock-music/actions ，每一个版本都是可以构建成功的
