### ISSUE TITLE
mgg格式解锁出现问题

### ISSUE THREAD

**Issue by Vinaaaaaaa** [ix64/unlock-music#83]
![image](https://user-images.githubusercontent.com/69341379/89621752-7537c400-d8c4-11ea-874f-464e39454b23.png)

**Comment by ix64** [comment]
提供样本文件，查看Wiki和 #51，是否为已知问题

**Comment by Vinaaaaaaa** [comment]
> 提供样本文件，查看Wiki和[＃51](https://github.com/ix64/unlock-music/issues/51)，是否为已知问题

链接：https://pan.baidu.com/s/1-_Jj9xUfjnTnUrcKZiQA7A 
提取码：k945
该文件夹内所有均出现问题，可选择1-2个尝试。

**Comment by ix64** [comment]
duplicated with #51
