### ISSUE TITLE
蝦米音樂好像更新了加密

### ISSUE THREAD

**Issue by ThankYouFreeMusic** [ix64/unlock-music#84]
關詩敏的新專輯「MASTERPIECE」
SQ無損音質，UNLOCK以後無法播放。（更改後綴名也無法播放）
原始數據：
链接：https://pan.baidu.com/s/1WDnO9LiC8040atf2cCVhlw  提取码：98i3
您有空方便看一看嗎？

**Comment by ThankYouFreeMusic** [comment]
蝦米音樂關詩敏的新專輯「MASTERPIECE」SQ無損音質的原始數據：
https://pan.baidu.com/s/1d4OAVw3g2WC40mPC62tzoQ 提取码：4575 
您可以抽空看一下麼？

**Comment by Unknow-404** [comment]
您分享的是wav文件

**Comment by ThankYouFreeMusic** [comment]
是的，因為用的是PC端WIN的客戶端下載的。安卓APP下的也是一樣的
WIN客戶端下載的後綴就是WAV，但是也是加密的，和XM是一樣的

**Comment by ix64** [comment]
好的，稍后查看
