### ISSUE TITLE
是否可以保留原文件的专辑信息和歌手名称

### ISSUE THREAD

**Issue by sunguosu** [ix64/unlock-music#87]
**背景和说明**
解锁后的文件，在导入itunes后专辑信息和歌手名称丢失，如果解密后仍可保留就更方便一些了

**Comment by ix64** [comment]
所有音乐的meta数据都是保留的，且
来自QQ和网易云的文件会额外写入封面图像。
如有疑问请提供相应样本文件。


--------------原始邮件--------------
发件人："sunguosu "<notifications@github.com&gt;;
发送时间：2020年8月14日(星期五) 凌晨0:36
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ix64/unlock-music] 是否可以保留原文件的专辑信息和歌手名称 (#87)
-----------------------------------

 

 
背景和说明
 解锁后的文件，在导入itunes后专辑信息和歌手名称丢失，如果解密后仍可保留就更方便一些了
