### ISSUE TITLE
modern版本解压后，用chrome打开一直加载请求

### ISSUE THREAD

**Issue by issackwan1** [ix64/unlock-music#88]
![image](https://user-images.githubusercontent.com/36833745/90303239-01f30b00-dedf-11ea-9289-6704f3325eab.png)

两个js加载不出异常，然后一直在加载，然后report返回204

**Comment by ix64** [comment]
请查看README和Wiki

## 部署
- `legacy`版本 可以通过file协议访问，既本地运行
- `modern`版本，只能通过http/https协议访问
- 建议在线部署，以启用Web Worker，获得更好性能
- 如存在无法加载的问题
  - 检查是否直接运行未编译的源代码。
  - 检查是否使用了错误的版本（legacy/modern）。
