### ISSUE TITLE
Ogg格式转换不成功？是否支持该格式解码

### ISSUE THREAD

**Issue by issackwan1** [ix64/unlock-music#89]
Ogg格式转换不成功？是否支持该格式解码

**Comment by ix64** [comment]
ogg本就是开放格式，无加密，和mp3/flac一样。
解密出何种格式文件有你下载的源文件决定。

**Comment by ix64** [comment]
另外 请按照Issue Template的提示填写，否则，请先通过Telegram或Email寻求帮助

**Comment by issackwan1** [comment]
QMCogg和mgg呢？

**Comment by ix64** [comment]
> QMCogg和mgg呢？

支持qmcogg，以及旧版QQ音乐产生的mgg
