### ISSUE TITLE
有个加密格式tkm，请求支持

### ISSUE THREAD

**Issue by wuhang2003** [ix64/unlock-music#9]
需求相对较少，但还是提一下
样本在QQ音乐下载部分歌曲伴奏时出现

**Comment by qiwolf** [comment]
能不能解密后保留歌曲信息及封面图片？感谢🙏

**Comment by ix64** [comment]
> 需求相对较少，但还是提一下
> 样本在QQ音乐下载部分歌曲伴奏时出现

请提供样本

**Comment by ix64** [comment]
> 能不能解密后保留歌曲信息及封面图片？感谢🙏

解密后是否包含歌曲信息、和封面图片由源文件本身决定。

**Comment by wuhang2003** [comment]
> > 需求相对较少，但还是提一下
> > 样本在QQ音乐下载部分歌曲伴奏时出现
> 
> 请提供样本

样本：https://send.firefox.com/download/a1a7805194a7317c/#9NPAG3XaEoPei8ULPUrxTA
