### ISSUE TITLE
离线下载部署的无法解析kgm、kgma音乐

### ISSUE THREAD

**Issue by ljhmily** [ix64/unlock-music#92]
- [x] 我确认已经搜索过Issue不存并确认相同的Issue
- [ ] 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）

**Bug描述**

离线下载部署的无法解析kgm、kgma音乐，加载提示：
出现问题
加载Kgm/Vpr Mask数据失败，Elize - About This Girl.kgm，参考使用提示

**复现方法**

离线部署后打开index.html，并导入kgm、kgma文件

**程序截图或者Console报错信息**
出现问题
加载Kgm/Vpr Mask数据失败，Elize - About This Girl.kgm，参考使用提示

**环境信息:**

 - 操作系统和浏览器：windows7 Chrome80
 - 程序版本：音乐解锁(v1.6.2)
 - 获取音乐文件所使用的客户端及其版本信息：酷狗8.x

**附加信息**
其他能够帮助确认问题的信息

**Comment by ix64** [comment]
问题已确认，将于下一版本进行修复。
此问题是因xhr无法加载本地资源引起。
感谢反馈。





--------------原始邮件--------------
发件人："Liu "<notifications@github.com&gt;;
发送时间：2020年8月29日(星期六) 上午10:20
收件人："ix64/unlock-music" <unlock-music@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[ix64/unlock-music] 离线下载部署的无法解析kgm、kgma音乐 (#92)
-----------------------------------

 

  
 我确认已经搜索过Issue不存并确认相同的Issue
 
 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）
  
Bug描述
 
离线下载部署的无法解析kgm、kgma音乐，加载提示：
 出现问题
 加载Kgm/Vpr Mask数据失败，Elize - About This Girl.kgm，参考使用提示
 
复现方法
 
离线部署后打开index.html，并导入kgm、kgma文件
 
程序截图或者Console报错信息
 出现问题
 加载Kgm/Vpr Mask数据失败，Elize - About This Girl.kgm，参考使用提示
 
环境信息:
  
操作系统和浏览器：windows7 Chrome80
 
程序版本：音乐解锁(v1.6.2)
 
获取音乐文件所使用的客户端及其版本信息：酷狗8.x
  
附加信息
 其他能够帮助确认问题的信息

**Comment by ix64** [comment]
暂时无解。本地请同时使用[CLI版本工具](https://github.com/ix64/unlock-music/wiki/%E5%85%B6%E4%BB%96%E9%9F%B3%E4%B9%90%E6%A0%BC%E5%BC%8F%E5%B7%A5%E5%85%B7#%E9%85%B7%E7%8B%97%E9%9F%B3%E4%B9%90-kgmvpr%E8%A7%A3%E9%94%81%E5%B7%A5%E5%85%B7)来进行解锁。

**Comment by ix64** [comment]
程序中已添加提示。此Issue将关闭。
