### ISSUE TITLE
Error: gg audio-codec not recognized

### ISSUE THREAD

**Issue by Unknow-404** [ix64/unlock-music#93]
- [ ] 我确认已经搜索过Issue不存并确认相同的Issue
- [ ] 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）

**复现方法**
[Fly Away - TheFatRat _ Anjulie.zip](https://github.com/ix64/unlock-music/files/5146468/Fly.Away.-.TheFatRat._.Anjulie.zip)

**程序截图或者Console报错信息**
Error: gg audio-codec not recognized (id=,:jv{)，Fly Away - TheFatRat _ Anjulie.mgg

**环境信息:**

 - 操作系统和浏览器：Windows10, Chrome
 - 程序版本：1.6.2
 - 获取音乐文件所使用的客户端及其版本信息：Windows QQ音乐 17.13

**Comment by ix64** [comment]
与 https://github.com/ix64/unlock-music/wiki/%E4%BD%BF%E7%94%A8%E6%8F%90%E7%A4%BA#%E5%85%B3%E4%BA%8Eqq%E9%9F%B3%E4%B9%90mflacmgg%E6%A0%BC%E5%BC%8F #51 所描述一致。
