### ISSUE TITLE
解码某些qmcflac出错：FourCC contains invalid characters: f4 57 fa fc

### ISSUE THREAD

**Issue by bqw5354** [ix64/unlock-music#95]
- [Yes] 我确认已经搜索过Issue不存并确认相同的Issue
- [Yes] 我认为这是程序导致的问题（如不确认，请先通过Telegram或者Email进行咨询）

**Bug描述**

我在QQ音乐中下载到的qmcflac大部分可以解码，但有一些会报错如下：
Error: FourCC contains invalid characters: f4 57 fa fc

**复现方法**

音乐文件在这里：
https://pan.baidu.com/s/1O6zdOHRazPVobHH2ArzYvQ
提取码：i8ff
将此文件拖到转换器就报错

**程序截图或者Console报错信息**
![Capture](https://user-images.githubusercontent.com/62192764/92034088-ba6fda00-ed3a-11ea-8435-f620efcdb2ce.JPG)

**环境信息:**

 - 操作系统和浏览器：Win10, Chrome
 - 程序版本：v1.6.3，访问自此链接：https://ix64.github.io/unlock-music/
 - 获取音乐文件所使用的客户端及其版本信息：QQ音乐 iOS 10.3.0 上传至微云再下载至电脑

**附加信息**
第一次在GitHub发言，如有不妥请多多包涵

**Comment by ix64** [comment]
更像是文件损坏，尝试重新下载一遍？

**Comment by bqw5354** [comment]
直接在电脑下载就可以转，从手机上传到微盘再下载就有些可以有些不可以，以后不用微云了。
